import test from "node:test";
import assert from "node:assert/strict";
import * as THREE from "three";
import {acrylicContours,signedArea,containsPoint} from "../app/design-keychain/acrylic-geometry.mjs";
function mask(width,height,opaque=()=>true){const data=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++)data[(y*width+x)*4+3]=opaque(x,y)?255:0;return {data,width,height}}
function geometry(loops){const outer=loops.filter(p=>signedArea(p)<0),holes=loops.filter(p=>signedArea(p)>0);const shapes=outer.map(points=>{const shape=new THREE.Shape(points.map(p=>new THREE.Vector2(p.x,p.y)));for(const h of holes)if(containsPoint(points,h[0]))shape.holes.push(new THREE.Path(h.map(p=>new THREE.Vector2(p.x,p.y))));return shape});const g=new THREE.ExtrudeGeometry(shapes,{depth:2.5,bevelEnabled:false});g.translate(0,0,-1.25);g.computeBoundingBox();return g}
test("solid artwork creates one acrylic outline with a real ring hole and 2.5mm depth",()=>{const loops=acrylicContours(mask(40,40),40,40,{x:20,y:-3});assert.equal(loops.filter(p=>signedArea(p)<0).length,1);const holes=loops.filter(p=>signedArea(p)>0);assert.equal(holes.length,1);assert.ok(containsPoint(holes[0],{x:0,y:23}));assert.ok(Math.abs(signedArea(holes[0])-Math.PI*1.5**2)<.6);const g=geometry(loops);assert.ok(Math.abs(g.boundingBox.max.z-g.boundingBox.min.z-2.5)<1e-5);assert.ok(Math.abs(g.boundingBox.min.x+21)<.22);assert.ok(Math.abs(g.boundingBox.max.y-26)<.22);const ray=new THREE.Raycaster(new THREE.Vector3(0,23,10),new THREE.Vector3(0,0,-1)),mesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));mesh.updateMatrixWorld();assert.equal(ray.intersectObject(mesh).length,0);ray.set(new THREE.Vector3(0,0,10),new THREE.Vector3(0,0,-1));assert.ok(ray.intersectObject(mesh).length>0);mesh.material.dispose();g.dispose()});
test("transparent interior artwork areas remain acrylic instead of becoming accidental cut holes",()=>{const loops=acrylicContours(mask(60,60,(x,y)=>!(x>20&&x<40&&y>20&&y<40)),40,40,{x:20,y:-3});assert.equal(loops.filter(p=>signedArea(p)>0).length,1)});
test("separate artwork islands remain separate and can be flagged for graphic review",()=>{const loops=acrylicContours(mask(100,60,(x)=>x<25||x>75),50,30,{x:6,y:-3});assert.equal(loops.filter(p=>signedArea(p)<0).length,2)});
test("side hole follows millimetre coordinates for landscape and portrait art",()=>{for(const [w,h] of [[80,8],[8,80]]){const loops=acrylicContours(mask(100,100),w,h,{x:w+3,y:h/2});const holes=loops.filter(p=>signedArea(p)>0);assert.equal(holes.length,1);assert.ok(containsPoint(holes[0],{x:w/2+3,y:0}));const g=geometry(loops);for(const value of g.attributes.position.array)assert.ok(Number.isFinite(value));g.dispose()}});
