import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import * as vatPolicy from '../app/vat-collection-policy.mjs';
function load(path,deps={}){const exports={};runInNewContext(ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require(name){if(!(name in deps))throw Error(`Unexpected dependency ${name}`);return deps[name];},Request,Response,File,FormData,URL,crypto,console,TextEncoder,Uint8Array,Uint32Array,Date});return exports;}
function setup(t){
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec('PRAGMA foreign_keys=ON');
 const dir=new URL('../drizzle/',import.meta.url);for(const f of readdirSync(dir).filter(x=>x.endsWith('.sql')).sort())for(const m of readFileSync(new URL(f,dir),'utf8').matchAll(/(?:CREATE TABLE [\s\S]*?;|CREATE (?:UNIQUE )?INDEX [\s\S]*?;|ALTER TABLE [\s\S]*?;)/g))db.exec(m[0]);
 db.prepare('INSERT INTO vat_collection_settings(id,mode) VALUES (1,?)').run(vatPolicy.VAT_TRANSITION);
 let failBatch=false;const adapter={prepare(sql){const statement=db.prepare(sql);function bound(args=[]){return{bind(...values){return bound(values);},async first(){return statement.get(...args)||null;},async all(){return{results:statement.all(...args)};},async run(){statement.run(...args);return{success:true};}};}return bound();},async batch(statements){db.exec('BEGIN');try{const results=[];for(const [i,s]of statements.entries()){results.push(await s.run());if(failBatch&&i===1)throw Error('Injected database failure');}db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};
 const blobs=new Map(),mail=[],pending=[];const runtime={DB:adapter,ORDER_FILES:{async put(key,bytes){blobs.set(key,bytes);},async get(key){return blobs.has(key)?{body:blobs.get(key)}:null;}},MEMBER_EMAIL_FROM:'orders@k2group.site',MEMBER_EMAIL:{async send(message){mail.push(message);}}};
 const workers={env:runtime,waitUntil(p){pending.push(p);}};t.after(async()=>{await Promise.all(pending);});
 const shared=load('../app/member-shared.ts');const auth=load('../app/member-auth.ts',{'cloudflare:workers':workers,'./member-shared':shared});const email=load('../app/member-email.ts',{'./member-shared':shared});
 const pricing=load('../app/pricing-config.ts');const calculation=load('../app/customer-checkout.ts',{'./member-auth':auth,'./pricing-config':pricing,'./vat-collection-policy.mjs':vatPolicy});
 const authRoute=load('../app/api/member/auth/route.ts',{'../../../member-auth':auth,'../../../member-email':email});
 const quotes=load('../app/api/member/quote/route.ts',{'../../../member-auth':auth,'../../../customer-checkout':calculation,'../../../vat-collection-policy.mjs':vatPolicy});
 const orders=load('../app/api/member/orders/route.ts',{'cloudflare:workers':workers,'../../../member-auth':auth,'../../../member-email':email});
 const details=load('../app/api/member/orders/[id]/route.ts',{'../../../../member-auth':auth,'../../../../order-status':load('../app/order-status.ts')});
 const downloads=load('../app/api/member/files/[id]/route.ts',{'../../../../member-auth':auth,'../../../../staff-auth':{getStaffUser:async()=>null,canViewOrderSlips:()=>false}});
 const request=(path,body,cookie='',origin='https://shop.test')=>new Request(`https://shop.test${path}`,{method:body?'POST':'GET',headers:{origin,cookie,...(body instanceof FormData?{}:{'content-type':'application/json'})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});
 async function start(address='customer@example.com'){const r=await authRoute.POST(request('/api/member/auth',{action:'start',email:address}));assert.equal(r.status,200,await r.clone().text());return{...(await r.json()),cookie:r.headers.getSetCookie()[0].split(';')[0],code:mail.at(-1).text.match(/\b\d{6}\b/)[0]};}
 async function login(address){const challenge=await start(address);const r=await authRoute.POST(request('/api/member/auth',{action:'verify',challengeId:challenge.challengeId,code:challenge.code},challenge.cookie));assert.equal(r.status,200,await r.clone().text());return{cookie:r.headers.getSetCookie().find(x=>x.startsWith('k2_customer_session=')).split(';')[0],...(await r.json())};}
 const input=()=>({items:[{id:crypto.randomUUID(),thickness:'2.5',width:5,height:5,quantity:100,sides:1,hardwareCode:'A',hardwareColor:'เงิน',packaging:'standard',files:[]}],customer:{name:'TEST LOCAL ONLY',phone:'0000000000',address:'Test address 123 Bangkok 10110',province:'Bangkok',requestedDate:new Date(Date.now()+86400000*10).toISOString().slice(0,10),invoiceRequested:false,companyName:'',taxId:'',taxAddress:'',branch:'สำนักงานใหญ่'}});
 async function quote(cookie,payload=input()){const r=await quotes.POST(request('/api/member/quote',payload,cookie));assert.equal(r.status,200,await r.clone().text());return r.json();}
 function orderRequest(cookie,q,files=[]){const form=new FormData();form.set('quoteId',q.quoteId);form.set('confirmed','1');for(const [key,file] of files)form.set(key,file);return request('/api/member/orders',form,cookie);}
 return{db,runtime,mail,pending,blobs,auth,authRoute,email,quotes,orders,details,downloads,request,start,login,input,quote,orderRequest,calculation,failBatch(){failBatch=true;}};
}
test('guest may read prices but cannot quote/create; rejects cross-origin auth',async t=>{const s=setup(t);assert.equal((await s.quotes.GET()).status,200);assert.equal((await s.quotes.POST(s.request('/quote',s.input()))).status,401);assert.equal((await s.orders.POST(s.request('/orders',new FormData()))).status,401);assert.equal((await s.authRoute.POST(s.request('/auth',{action:'start',email:'x@example.com'},'','https://evil.test'))).status,403);assert.equal(s.mail.length,0);});
test('OTP creates email-verified member, secure session and no staff privileges; replay and cross-browser denied',async t=>{const s=setup(t),c=await s.start('Person@EXAMPLE.com');assert.equal(c.email,'person@example.com');assert.equal(c.code.length,6);const stored=s.db.prepare('SELECT * FROM customer_email_challenges').get();assert.notEqual(stored.code_hash,c.code);assert.equal(s.mail[0].from.email,'orders@k2group.site');assert.equal(s.mail[0].from.name,'K2STUDIO');const body={action:'verify',challengeId:c.challengeId,code:c.code};assert.equal((await s.authRoute.POST(s.request('/auth',body))).status,400);const r=await s.authRoute.POST(s.request('/auth',body,c.cookie));assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/Secure/);assert.doesNotMatch(r.headers.get('set-cookie'),/k2_staff_session/);assert.equal((await s.authRoute.POST(s.request('/auth',body,c.cookie))).status,400);assert.equal(s.db.prepare('SELECT count(*) n FROM customer_members').get().n,1);assert.equal(s.db.prepare('SELECT count(*) n FROM staff_sessions').get().n,0);});
test('OTP five-attempt lock, expiration, blocked member and email failure do not grant session',async t=>{const s=setup(t),c=await s.start();for(let i=0;i<5;i++)assert.equal((await s.authRoute.POST(s.request('/auth',{action:'verify',challengeId:c.challengeId,code:c.code==='000000'?'111111':'000000'},c.cookie))).status,400);assert.equal((await s.authRoute.POST(s.request('/auth',{action:'verify',challengeId:c.challengeId,code:c.code},c.cookie))).status,400);const expired=await s.start('expired@example.com');s.db.prepare('UPDATE customer_email_challenges SET expires_at=0 WHERE id=?').run(expired.challengeId);assert.equal((await s.authRoute.POST(s.request('/auth',{action:'verify',challengeId:expired.challengeId,code:expired.code},expired.cookie))).status,400);const inactive=await s.login('inactive@example.com');s.db.prepare('UPDATE customer_members SET active=0 WHERE id=?').run(inactive.member.id);assert.equal((await s.authRoute.GET(s.request('/auth',undefined,inactive.cookie))).status,200);assert.equal((await (await s.authRoute.GET(s.request('/auth',undefined,inactive.cookie))).json()).member,null);s.runtime.MEMBER_EMAIL.send=async()=>{throw Error('Provider unavailable');};assert.equal((await s.authRoute.POST(s.request('/auth',{action:'start',email:'failed@example.com'}))).status,503);assert.ok(s.db.prepare("SELECT consumed_at FROM customer_email_challenges WHERE email='failed@example.com'").get().consumed_at);});
test('sign in existing email reuses member; logout and expired sessions revoked',async t=>{const s=setup(t),a=await s.login(),b=await s.login();assert.equal(a.member.id,b.member.id);assert.equal((await s.authRoute.POST(s.request('/auth',{action:'logout'},a.cookie))).status,200);assert.equal(await s.auth.getMember(s.request('/auth',undefined,a.cookie)),null);s.db.exec('UPDATE customer_sessions SET expires_at=0');assert.equal(await s.auth.getMember(s.request('/auth',undefined,b.cookie)),null);});
test('server ignores client money/payment/owner values, totals shipping and validates item color/files',async t=>{const s=setup(t),m=await s.login(),p=s.input();p.total=1;p.deposit_amount=99999;p.sales_owner_id=99;p.items[0].unitPrice=0.01;p.items[0].lineTotal=1;const q=await s.quote(m.cookie,p);assert.ok(q.quote.subtotal>1);assert.equal(q.quote.shipping,50);assert.equal(q.quote.total,q.quote.subtotal+50);p.items[0].hardwareColor='not-a-color';assert.equal((await s.quotes.POST(s.request('/quote',p,m.cookie))).status,400);p.items[0].hardwareColor='เงิน';p.items[0].files=[{name:'attack.html',type:'text/html',size:10,hash:'a'.repeat(64)}];assert.equal((await s.quotes.POST(s.request('/quote',p,m.cookie))).status,400);});
test('multiple lines saved atomically, duplicate confirmation creates one unpaid order and one email',async t=>{const s=setup(t),m=await s.login(),p=s.input();p.items.push({...p.items[0],id:crypto.randomUUID(),quantity:200});const q=await s.quote(m.cookie,p);const r=await s.orders.POST(s.orderRequest(m.cookie,q));assert.equal(r.status,201,await r.clone().text());const saved=await r.json();const retry=await s.orders.POST(s.orderRequest(m.cookie,q));assert.equal(retry.status,200,await retry.clone().text());assert.equal((await retry.json()).orderId,saved.orderId);await Promise.all(s.pending);const o=s.db.prepare('SELECT * FROM orders').get();assert.equal(Number(o.deposit_amount),0);assert.equal(Number(o.estimated_total)+Number(o.shipping_fee),q.quote.total);assert.equal(o.email,m.member.email);assert.equal(o.contact_channel,'customer_web');assert.equal(Number(o.sales_owner_id||0),0);assert.equal(s.db.prepare('SELECT count(*) n FROM order_items').get().n,2);assert.equal(s.db.prepare('SELECT count(*) n FROM orders').get().n,1);assert.equal(s.db.prepare('SELECT count(*) n FROM customer_order_links').get().n,1);assert.equal(s.db.prepare('SELECT count(*) n FROM order_status_history').get().n,1);assert.equal(s.db.prepare('SELECT count(*) n FROM order_payment_receipts').get().n,0);assert.equal(s.mail.length,2);assert.match(s.mail[1].text,/รอชำระเงิน/);});
test('another member cannot submit quote, read order or download private artwork',async t=>{const s=setup(t),a=await s.login('a@example.com'),b=await s.login('b@example.com'),p=s.input(),file=new File(['image-test'],'artwork.png',{type:'image/png'});p.items[0].files=[{name:file.name,type:file.type,size:file.size,hash:await s.auth.digest('image-test')}];const q=await s.quote(a.cookie,p);assert.equal((await s.orders.POST(s.orderRequest(b.cookie,q))).status,409);let r=await s.orders.POST(s.orderRequest(a.cookie,q,[[`file-${p.items[0].id}-0`,file]]));assert.equal(r.status,201,await r.clone().text());const {orderId}=await r.json();const context={params:Promise.resolve({id:String(orderId)})};assert.equal((await s.details.GET(s.request('/detail',undefined,b.cookie),context)).status,404);r=await s.details.GET(s.request('/detail',undefined,a.cookie),context);assert.equal(r.status,200);const detail=await r.json(),fileContext={params:Promise.resolve({id:detail.files[0].id})};assert.equal((await s.downloads.GET(s.request('/file',undefined,b.cookie),fileContext)).status,404);r=await s.downloads.GET(s.request('/file',undefined,a.cookie),fileContext);assert.equal(r.status,200);assert.equal(await r.text(),'image-test');assert.match(r.headers.get('content-disposition'),/^attachment/);assert.equal((await (await s.orders.GET(s.request('/orders',undefined,b.cookie))).json()).orders.length,0);await Promise.all(s.pending);});
test('missing/changed files, expired quote and changed VAT revision create no order',async t=>{const s=setup(t),m=await s.login(),p=s.input();p.items[0].files=[{name:'test.png',type:'image/png',size:4,hash:await s.auth.digest('abcd')}];const q=await s.quote(m.cookie,p);assert.equal((await s.orders.POST(s.orderRequest(m.cookie,q))).status,409);assert.equal((await s.orders.POST(s.orderRequest(m.cookie,q,[[`file-${p.items[0].id}-0`,new File(['efgh'],'test.png',{type:'image/png'})]]))).status,409);const q2=await s.quote(m.cookie);s.db.exec('UPDATE vat_collection_settings SET revision=2');assert.equal((await s.orders.POST(s.orderRequest(m.cookie,q2))).status,409);s.db.prepare('UPDATE customer_quotes SET expires_at=0 WHERE id=?').run(q.quoteId);assert.equal((await s.orders.POST(s.orderRequest(m.cookie,q))).status,409);assert.equal(s.db.prepare('SELECT count(*) n FROM orders').get().n,0);assert.equal(s.db.prepare('SELECT count(*) n FROM customer_order_links').get().n,0);});
test('database failure rolls back order, lines, ownership and email job',async t=>{const s=setup(t),m=await s.login(),q=await s.quote(m.cookie);s.failBatch();assert.equal((await s.orders.POST(s.orderRequest(m.cookie,q))).status,503);for(const table of ['orders','order_items','customer_order_links','customer_email_jobs'])assert.equal(s.db.prepare(`SELECT count(*) n FROM ${table}`).get().n,0,table);});
test('email outbox failure leaves retryable job, never duplicates the saved order',async t=>{const s=setup(t),m=await s.login(),q=await s.quote(m.cookie);s.runtime.MEMBER_EMAIL.send=async()=>{throw Error('Offline');};const r=await s.orders.POST(s.orderRequest(m.cookie,q));assert.equal(r.status,201,await r.clone().text());await Promise.all(s.pending);const job=s.db.prepare('SELECT * FROM customer_email_jobs').get();assert.equal(job.state,'pending');assert.equal(job.attempts,1);assert.ok(job.available_at>Date.now());assert.equal(s.db.prepare('SELECT count(*) n FROM orders').get().n,1);});
test('spoofed SVG MIME never becomes inline executable artwork',async t=>{const s=setup(t),m=await s.login(),p=s.input(),body='<svg onload="alert(1)"></svg>',file=new File([body],'disguised.png',{type:'image/svg+xml'});p.items[0].files=[{name:file.name,type:file.type,size:file.size,hash:await s.auth.digest(body)}];const q=await s.quote(m.cookie,p),r=await s.orders.POST(s.orderRequest(m.cookie,q,[[`file-${p.items[0].id}-0`,file]]));assert.equal(r.status,201,await r.clone().text());assert.equal(s.db.prepare('SELECT artwork_type FROM orders').get().artwork_type,'application/octet-stream');await Promise.all(s.pending);});
