"use client";
import { lazy, Suspense, useEffect, useRef, useState, type RefObject } from "react";
import { calculatePrice, HARDWARE, HARDWARE_VARIANTS, hardwareImagePath } from "../pricing-config";
import { designDimensions } from "../customer-design.mjs";
import { openArt, removeEdgeBackground, holeOnSilhouette, exportProof, type Artwork } from "./image-tools";
import styles from "./designer.module.css";
import { QuantityPicker, HardwarePicker, DesignHelp } from "./ShoppingOptions";
const AcrylicPreview=lazy(()=>import("./AcrylicPreview").catch(()=>({default:()=> <p role="alert">เปิดภาพ 3D ไม่สำเร็จ กรุณากลับไปจัดแบบ 2D หรือรีเฟรชหน้าเพื่อลองอีกครั้ง</p>})));
type Item={id:number;line_no:number;item_name:string;quantity:number;print_sides:number;hardware_code:string;hardware_color:string};
type Order={orderNumber:string;canSubmit:boolean;items:Item[];receipts:Array<{id:number;createdAt:string}>};
const money=(n:number)=>n.toLocaleString("th-TH",{maximumFractionDigits:2});
function Proof({art,back,side,w,h,hole,guides,svgRef,onPointer}:{art:Artwork;back:Artwork|null;side:"front"|"back";w:number;h:number;hole:{x:number;y:number};guides:boolean;svgRef:RefObject<SVGSVGElement|null>;onPointer:(e:React.PointerEvent<SVGSVGElement>)=>void}){
 const x=(100-w)/2,y=(100-h)/2,hx=x+hole.x,hy=y+hole.y,isBack=side==="back",flip=isBack?"translate(100 0) scale(-1 1)":undefined,display=isBack?back:art;
 return <svg ref={svgRef} viewBox="-20 -30 140 150" role="img" aria-label={`ภาพตัวอย่าง${isBack?"ด้านหลัง":"ด้านหน้า"}`} onPointerMove={onPointer} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);onPointer(e)}}>
 <defs><filter id={`outline-${side}`} x="-20" y="-20" width="140" height="140" filterUnits="userSpaceOnUse"><feMorphology in="SourceAlpha" operator="dilate" radius="1" result="expanded"/><feFlood floodColor={guides?"#ed8153":"#ccdde4"} floodOpacity={guides?1:.65}/><feComposite in2="expanded" operator="in"/></filter><mask id={`mask-${side}`} maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100" style={{maskType:"alpha"}}><image href={art.url} x={x} y={y} width={w} height={h} transform={flip}/></mask></defs>
 <g transform={flip}><circle cx={hx} cy={hy} r="3" fill="#ccdde4" stroke={guides?"#ed8153":"#92aab5"} strokeWidth=".25"/></g>
 <image href={art.url} x={x} y={y} width={w} height={h} transform={flip} filter={`url(#outline-${side})`}/>
 {display&&<image href={display.url} x={x} y={y} width={w} height={h} preserveAspectRatio="xMidYMid meet" mask={`url(#mask-${side})`}/>}
 <g transform={flip}><circle cx={hx} cy={hy} r="1.5" fill="#f4f6f7" stroke="#526873" strokeWidth=".25"/></g>
 {guides&&<rect x={x} y={y} width={w} height={h} fill="none" stroke="#8198a4" strokeWidth=".15" strokeDasharray="1 1"/>}
 </svg>
}
export default function KeychainDesigner(){
 const [art,setArt]=useState<Artwork|null>(null),[back,setBack]=useState<Artwork|null>(null),[sameBack,setSameBack]=useState(false);
 const [size,setSize]=useState(50),[quantity,setQuantity]=useState(1),[sides,setSides]=useState<1|2>(1),[side,setSide]=useState<"front"|"back">("front"),[angle,setAngle]=useState(-90);
 const [hardware,setHardware]=useState("A"),[color,setColor]=useState("เงิน");
 const [guides,setGuides]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[receipt,setReceipt]=useState<number|null>(null);
 const [prices,setPrices]=useState<Record<string,number>|null>(null),[token,setToken]=useState(""),[order,setOrder]=useState<Order|null>(null),[itemId,setItemId]=useState(0),[orderError,setOrderError]=useState("");
 const [submissionId,setSubmissionId]=useState("");
 const [previewMode,setPreviewMode]=useState<"2d"|"3d">("2d");
 const inputRef=useRef<HTMLInputElement>(null),frontRef=useRef<SVGSVGElement>(null),backRef=useRef<SVGSVGElement>(null);
 useEffect(()=>{const controller=new AbortController();fetch("/api/pricing",{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{hardwarePrices:Record<string,number>}>}).then(d=>setPrices(d.hardwarePrices)).catch(()=>{});const t=new URLSearchParams(window.location.search).get("order")||"";setToken(t);if(t){fetch(`/api/orders/${encodeURIComponent(t)}/customer-design`,{signal:controller.signal}).then(async r=>{const d=await r.json() as Order & {error?:string};if(!r.ok)throw Error(d.error);return d}).then((d:Order)=>{setOrder(d);if(d.items.length){const i=d.items[0];setItemId(i.id);setQuantity(i.quantity);setSides(i.print_sides===2?2:1);if(HARDWARE_VARIANTS[i.hardware_code]){setHardware(i.hardware_code);setColor(HARDWARE_VARIANTS[i.hardware_code].includes(i.hardware_color)?i.hardware_color:HARDWARE_VARIANTS[i.hardware_code][0])}}}).catch(e=>{if(e.name!=="AbortError")setOrderError(e.message)})}return()=>controller.abort()},[]);
 useEffect(()=>{setConfirmed(false);setReceipt(null);setSubmissionId(crypto.randomUUID())},[art,back,sameBack,size,quantity,sides,angle,hardware,color,itemId]);
 useEffect(()=>()=>{if(art)URL.revokeObjectURL(art.url)},[art]);useEffect(()=>()=>{if(back)URL.revokeObjectURL(back.url)},[back]);
 async function load(file:File|undefined,isBack=false){if(!file)return;setBusy(true);setError("");try{const result=await openArt(file);(isBack?setBack:setArt)(result)}catch(e){setError(e instanceof Error?e.message:"เปิดภาพไม่ได้")}finally{setBusy(false)}}
 async function remove(){const target=side==="back"&&!sameBack?back:art;if(!target)return;setBusy(true);setError("");try{const next=await removeEdgeBackground(target);(side==="back"&&!sameBack?setBack:setArt)(next)}catch(e){setError(e instanceof Error?e.message:"ลบพื้นหลังไม่ได้")}finally{setBusy(false)}}
 const aspect=art?art.width/art.height:1,w=aspect>=1?size:size*aspect,h=aspect>=1?size/aspect:size,hole=holeOnSilhouette(art,w,h,angle),dims=designDimensions(size,aspect,hole),backArt=sameBack?art:back;
 const quote=calculatePrice({thickness:"2.5",width:dims.totalWidth/10,height:dims.totalHeight/10,quantity,sides,hardwareCode:hardware,packaging:"standard",hardwarePrice:prices?.[hardware]});
 function move(e:React.PointerEvent<SVGSVGElement>){if(e.buttons!==1||busy)return;const ctm=e.currentTarget.getScreenCTM();if(!ctm)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());setAngle(Math.round(Math.atan2(point.y-50,(side==="back"?-1:1)*(point.x-50))*180/Math.PI))}
 async function proof(){if(!frontRef.current)throw Error("กรุณาอัปโหลดภาพก่อน");const views=[frontRef.current];if(sides===2&&backRef.current)views.push(backRef.current);return exportProof(views,`${dims.totalWidth.toFixed(1)} x ${dims.totalHeight.toFixed(1)} mm | acrylic 2.5 mm | ${quantity} pcs | ${hardware} ${color} | REF ONLY / GRAPHIC REVIEW REQUIRED`)}
 async function download(){setBusy(true);setError("");try{const url=URL.createObjectURL(await proof()),a=document.createElement("a");a.href=url;a.download="K2-keychain-proof.png";a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){setError(e instanceof Error?e.message:"สร้างภาพตัวอย่างไม่ได้")}finally{setBusy(false)}}
 async function submit(){if(!art||!order||!confirmed||!hole.valid)return;setBusy(true);setError("");try{const f=new FormData();f.set("submission_id",submissionId);f.set("confirmed","1");f.set("spec",JSON.stringify({schemaVersion:1,itemId,material:"clear_acrylic",thicknessMm:2.5,sizeMm:size,aspect,quantity,sides,hardwareCode:hardware,hardwareColor:color,hole:{x:hole.x,y:hole.y}}));f.set("original_front",art.original);f.set("front",art.processed,"front.png");if(sides===2){if(!backArt)throw Error("กรุณาเลือกภาพด้านหลัง");f.set("original_back",backArt.original);f.set("back",backArt.processed,"back.png")}f.set("preview",await proof(),"proof.png");const response=await fetch(`/api/orders/${token}/customer-design`,{method:"POST",body:f});const data=await response.json() as {error?:string;receiptId:number};if(!response.ok)throw Error(data.error||"ส่งแบบไม่ได้");setReceipt(data.receiptId)}catch(e){setError(e instanceof Error?e.message:"ส่งแบบไม่ได้ กรุณาลองอีกครั้ง")}finally{setBusy(false)}}
 const canSend=Boolean(art&&hole.valid&&(! (sides===2)||backArt)&&confirmed&&order?.canSubmit&&itemId&&!busy&&!receipt);
 return <main className={styles.designer}>
 <header className={styles.header}><a href="/" className={styles.brand}>K2<span>STUDIO</span></a><span>ออกแบบพวงกุญแจ</span><a href="/price-list">ตารางราคา ↗</a></header>
 <nav className={styles.steps} aria-label="ขั้นตอนออกแบบพวงกุญแจ">
 <a href="#design-art"><b>01</b><span>อัปโหลดภาพ</span></a><a href="#design-size"><b>02</b><span>ขนาดและรูห่วง</span></a><a href="#design-hardware"><b>03</b><span>เลือกอะไหล่</span></a><a href="#design-quantity"><b>04</b><span>จำนวนและราคา</span></a><a href="#design-confirm"><b>05</b><span>ตรวจและส่งแบบ</span></a>
 </nav><div className={styles.workspace}>
 <fieldset disabled={busy} className={styles.controls}>
 <span className={styles.eyebrow}>แบบของคุณ</span><h1>เปลี่ยนภาพโปรด<br/>เป็นพวงกุญแจ</h1><p>อะคริลิกใส 2.5 มม. · พิมพ์ UV</p>
 {order&&<label>ออเดอร์ {order.orderNumber}<select value={itemId} onChange={e=>setItemId(Number(e.target.value))}>{order.items.map(i=><option key={i.id} value={i.id}>{i.line_no} · {i.item_name}</option>)}</select></label>}
 <section id="design-art"><h2>01 ภาพพิมพ์</h2><label className={styles.upload}>＋ {art?"เปลี่ยนภาพด้านหน้า":"อัปโหลดภาพของคุณ"}<input ref={inputRef} type="file" accept="image/png,image/jpeg" onChange={e=>load(e.target.files?.[0])}/></label><small>PNG โปร่งใส หรือ JPG ไม่เกิน 15 MB</small>{art&&<p className={styles.filename}>{art.name}</p>}
 <div className={styles.segment}><button aria-pressed={sides===1} onClick={()=>{setSides(1);setSide("front")}}>พิมพ์ด้านเดียว</button><button aria-pressed={sides===2} onClick={()=>setSides(2)}>พิมพ์สองด้าน</button></div>
 {sides===2&&<><label><input type="checkbox" checked={sameBack} onChange={e=>setSameBack(e.target.checked)}/> ใช้ภาพเดียวกันทั้งสองด้าน</label>{!sameBack&&<label className={styles.upload}>＋ {back?"เปลี่ยนภาพด้านหลัง":"อัปโหลดภาพด้านหลัง"}<input type="file" accept="image/png,image/jpeg" onChange={e=>load(e.target.files?.[0],true)}/></label>}</>}
 <button className={styles.secondary} disabled={!art} onClick={remove}>ลบพื้นหลังสีเรียบ · {side==="front"?"ด้านหน้า":"ด้านหลัง"}</button><small>เหมาะกับพื้นหลังสีเดียว ภาพฉากซับซ้อนให้เตรียม PNG โปร่งใสหรือให้กราฟิกช่วยตรวจ</small>{art&&<button className={styles.textButton} onClick={()=>load((side==="back"&&!sameBack?back:art)?.original,side==="back"&&!sameBack)}>คืนภาพต้นฉบับด้านที่กำลังดู</button>}
 </section>
 <section id="design-size"><h2>02 ขนาดภาพและรูห่วง</h2><label>ด้านยาวของภาพ (มม.)<input type="number" min="10" max="80" step="1" value={size} onChange={e=>setSize(Math.max(10,Math.min(80,Number(e.target.value)||10)))}/></label><small>ก่อนเพิ่มขอบใส 1 มม. และหูห่วง ขนาดรวมแสดงใต้ภาพ</small><div className={styles.segment}>{[["ซ้าย",180],["บน",-90],["ขวา",0]].map(([label,a])=><button key={label} onClick={()=>setAngle(Number(a))}>{label}</button>)}</div><label>ตำแหน่งรูห่วง {angle}°<input type="range" min="-180" max="180" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label><small>รูห่วงตัวอย่าง 3 มม. กราฟิกตรวจระยะก่อนผลิต</small>{art&&!hole.valid&&<p className={styles.error}>ตำแหน่งนี้ไม่มีเนื้อภาพรองรับ กรุณาเลื่อนรูไปตำแหน่งอื่น</p>}</section>
 <section id="design-hardware"><h2>03 เลือกอะไหล่จากภาพ</h2><HardwarePicker value={hardware} prices={prices} onChange={code=>{setHardware(code);setColor(HARDWARE_VARIANTS[code][0])}}/><label>สี / รูปแบบย่อย<select value={color} onChange={e=>setColor(e.target.value)}>{HARDWARE_VARIANTS[hardware].map(c=><option key={c}>{c}</option>)}</select></label></section>
 </fieldset>
 <section className={styles.stageWrap} aria-label="ภาพตัวอย่างพวงกุญแจ"><div className={styles.stageSticky}><div className={styles.segment} aria-label="รูปแบบภาพตัวอย่าง"><button aria-pressed={previewMode==="2d"} onClick={()=>setPreviewMode("2d")}>จัดแบบ 2D</button><button disabled={!art||!hole.valid} aria-pressed={previewMode==="3d"} onClick={()=>setPreviewMode("3d")}>ดูอะคริลิก 3D · 360°</button></div>
 {previewMode==="3d"&&art&&<Suspense fallback={<p role="status">กำลังเปิดภาพตัวอย่าง 3D…</p>}><AcrylicPreview art={art} back={backArt} w={w} h={h} hole={hole} sides={sides}/></Suspense>}
 <div style={{display:previewMode==="2d"?"block":"none"}}><div className={styles.toolbar}><div className={styles.segment}><button aria-pressed={side==="front"} onClick={()=>setSide("front")}>ด้านหน้า</button><button disabled={sides===1} aria-pressed={side==="back"} onClick={()=>setSide("back")}>ด้านหลัง</button></div><label><input type="checkbox" checked={guides} onChange={e=>setGuides(e.target.checked)}/> แสดงเส้นตัด</label></div>
 <div className={styles.stage}>{art?<>{(["front","back"] as const).map(view=><div key={view} className={styles.proof} style={{display:side===view?"block":"none"}}><Proof art={art} back={backArt} side={view} w={w} h={h} hole={hole} guides={guides} svgRef={view==="front"?frontRef:backRef} onPointer={move}/></div>)}</>:<button className={styles.empty} onClick={()=>inputRef.current?.click()}><span>＋</span><b>เริ่มด้วยภาพของคุณ</b><p>รูปสัตว์เลี้ยง ภาพวาด หรือโลโก้</p><small>อัปโหลดภาพเพื่อดูตัวอย่างชิ้นงาน</small></button>}</div>
 <div className={styles.stageFoot}><span>{art?`${dims.totalWidth.toFixed(1)} × ${dims.totalHeight.toFixed(1)} มม. รวมขอบและหูห่วง`:"ภาพตัวอย่างจะแสดงที่นี่"}</span><span>ขอบใส 1 มม.</span></div><p className={styles.caption}>ลากบนพื้นที่ภาพเพื่อเลือกตำแหน่งรูใส่ห่วง · ภาพตัวอย่างต้องผ่านกราฟิกตรวจก่อนผลิต</p>{side==="back"&&sides===2&&<p className={styles.caption}>ด้านหลังใช้รูปทรงตัดเดียวกับด้านหน้า ภาพที่อยู่นอกชิ้นงานจะถูกซ่อน</p>}
 </div></div></section>
 <aside className={styles.summary}><span className={styles.eyebrow}>สรุปแบบ</span><h2>พวงกุญแจของคุณ</h2><div className={styles.hardware}><span>อะไหล่ที่เลือก</span><img src={hardwareImagePath(hardware)} alt={HARDWARE.find(a=>a.code===hardware)?.name}/><div><b>รหัส {hardware} · {color}</b><small>{HARDWARE.find(a=>a.code===hardware)?.name}</small><small>ภาพอ้างอิงรูปทรง สีตามที่เลือก</small></div></div><dl><div><dt>วัสดุ</dt><dd>อะคริลิกใส 2.5 มม.</dd></div><div><dt>การพิมพ์</dt><dd>{sides===1?"ด้านเดียว พิมพ์กลับ":"สองด้าน C1 / ขาว / C2"}</dd></div><div><dt>อะไหล่</dt><dd>{hardware} · {color}</dd></div><div><dt>ขนาดคิดราคา</dt><dd>{quote.size} ซม.</dd></div></dl><QuantityPicker quantity={quantity} setQuantity={setQuantity} disabled={busy} width={dims.totalWidth/10} height={dims.totalHeight/10} sides={sides} hardwareCode={hardware} hardwarePrice={prices?.[hardware]}/><dl><div><dt>ราคาฐาน / ชิ้น</dt><dd>฿{money(quote.base)}</dd></div><div><dt>พิมพ์ด้านที่สอง / ชิ้น</dt><dd>+฿{money(quote.print)}</dd></div><div><dt>อะไหล่ / ชิ้น</dt><dd>+฿{money(quote.hardware)}</dd></div></dl><div className={styles.price} aria-live="polite" aria-atomic="true"><small>ราคาประเมิน {prices?"จากราคากลาง":"จากตารางมาตรฐาน"}</small><strong>฿{money(quote.total)}</strong><span>฿{money(quote.unit)} / ชิ้น</span></div><small>รวมซองใส · ไม่รวม VAT และค่าส่ง<br/>สเปกที่เปลี่ยนต้องให้ทีมงานตรวจราคาออเดอร์อีกครั้ง</small>
 <section id="design-confirm" className={styles.review}><h2>05 ตรวจแบบก่อนส่ง</h2><ul><li>{art?"✓ มีภาพด้านหน้าแล้ว":"○ รอภาพด้านหน้า"}</li>{sides===2&&<li>{backArt?"✓ มีภาพด้านหลังแล้ว":"○ รอภาพด้านหลัง"}</li>}<li>{art&&hole.valid?"✓ มีตำแหน่งรูห่วงแล้ว":"○ อัปโหลดภาพและกำหนดรูห่วง"}</li></ul><small>ตรวจภาพ ขนาด และอะไหล่ให้ครบ ทีมกราฟิกจะตรวจความพร้อมผลิตอีกครั้ง</small>
 <button className={styles.secondary} disabled={!art||busy||(sides===2&&!backArt)} onClick={download}>ดาวน์โหลดภาพตัวอย่าง</button>
 {order?<><label className={styles.confirm}><input disabled={busy||!!receipt} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> ฉันตรวจภาพทั้งสองด้านตามที่เลือก ขนาด และอะไหล่แล้ว ยืนยันส่งให้กราฟิกตรวจ</label><button className={styles.primary} disabled={!canSend} onClick={submit}>{busy?"กำลังเตรียมและส่งแบบ…":"ยืนยันแบบ ส่งให้กราฟิกตรวจ"}</button>{!order.canSubmit&&<p className={styles.notice}>ออเดอร์อยู่ในขั้นตรวจอนุมัติหรือผลิตแล้ว กรุณาติดต่อทีมงานก่อนส่งแบบใหม่</p>}{!order.items.length&&<p className={styles.notice}>ออเดอร์นี้ไม่มีรายการพวงกุญแจอะคริลิก 2.5 มม.</p>}</>:<p className={styles.notice}>{orderError||"ทดลองออกแบบและดาวน์โหลดภาพได้ หากต้องการส่งเข้าระบบ กรุณาเปิดจากลิงก์ออกแบบที่ทีมงานส่งให้สำหรับออเดอร์ของคุณ"}</p>}
 {receipt&&<div role="status" className={styles.success}><b>รับแบบยืนยัน #{receipt} แล้ว</b><p>รอกราฟิกตรวจ ยังไม่ส่งผลิต</p><a href={`/track/${token}`}>ดูสถานะออเดอร์ →</a></div>}{error&&<p role="alert" className={styles.error}>{error}</p>}
 </section></aside></div><DesignHelp/></main>
}
