"use client";
import { calculatePrice, HARDWARE, PRICE_TABLES, hardwareImagePath } from "../pricing-config";
import styles from "./designer.module.css";
const money=(n:number)=>n.toLocaleString("th-TH",{maximumFractionDigits:2});
const thresholds=[1,11,30,50,200,500,1000,3000,5000,10000,20000,30000];
export function QuantityPicker({quantity,setQuantity,disabled,...spec}:{quantity:number;setQuantity:(n:number)=>void;disabled:boolean;width:number;height:number;sides:1|2;hardwareCode:string;hardwarePrice?:number}){
 const getQuote=(count:number)=>calculatePrice({...spec,quantity:count,thickness:"2.5",packaging:"standard"});
 const quote=getQuote(quantity),current=thresholds.findLastIndex(n=>quantity>=n),next=thresholds[current+1],nextQuote=next?getQuote(next):null;
 const row=(minimum:number,index:number)=>{const active=current===index,preview=getQuote(minimum),max=thresholds[index+1];const label=index<6?PRICE_TABLES.retail.tiers[index]:max?`${money(minimum)}–${money(max-1)}`:`${money(minimum)}+`;
 return <button type="button" key={minimum} disabled={disabled} aria-pressed={active} className={styles.rateRow} onClick={()=>setQuantity(minimum)} aria-label={`เลือก ${money(minimum)} ชิ้น เรท ${label} ชิ้น ราคา ${money(preview.unit)} บาทต่อชิ้น`}><span><b>{label}</b>{active&&<small>เรทที่ใช้อยู่</small>}</span><strong>฿{money(preview.unit)}<small>/ ชิ้น</small></strong></button>};
 return <section id="design-quantity" className={styles.quantitySection}><h2>04 จำนวนและราคา</h2><small>ราคาต่อชิ้นรวมการพิมพ์และอะไหล่ที่เลือก</small><label>จำนวนต่อแบบ<input disabled={disabled} type="number" min="1" max="1000000" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(1000000,Math.floor(Number(e.target.value)||1))))}/></label><div className={styles.rateHead}><span>จำนวน (ชิ้น)</span><span>บาท / ชิ้น</span></div><div className={styles.rateList}>{thresholds.slice(0,6).map(row)}</div><details className={styles.factoryRates} open={quantity>=1000?true:undefined}><summary>เรทโรงงาน 1,000 ชิ้นขึ้นไป</summary>{thresholds.slice(6).map((n,i)=>row(n,i+6))}</details>{nextQuote&&nextQuote.unit<quote.unit&&<p className={styles.nextRate}>เมื่อสั่ง {money(next)} ชิ้น ราคาลดเป็น <b>฿{money(nextQuote.unit)} / ชิ้น</b><small>ยอดรวม ฿{money(nextQuote.total)} · ไม่รวม VAT และค่าส่ง</small><button type="button" disabled={disabled} onClick={()=>setQuantity(next)}>เปลี่ยนเป็น {money(next)} ชิ้น →</button></p>}<small>แตะแถวราคาเพื่อเลือกจำนวนเริ่มต้นของเรท หรือกรอกจำนวนเองด้านบน</small></section>
}
export function HardwarePicker({value,prices,onChange}:{value:string;prices:Record<string,number>|null;onChange:(code:string)=>void}){
 return <><small>ดูรูปทรงและราคาเพิ่มต่อชิ้น แล้วเลือกสีด้านล่าง</small><div className={styles.hardwareGrid} role="group" aria-label="รูปแบบอะไหล่">{HARDWARE.map(item=>{const price=prices?.[item.code]??item.price;return <button type="button" key={item.code} aria-pressed={value===item.code} onClick={()=>onChange(item.code)} title={item.name}><img loading="lazy" src={hardwareImagePath(item.code)} alt=""/><b>{item.code}{value===item.code?" · เลือกแล้ว":""}</b><span>{item.name}</span><strong>{price===0?"รวมในราคา":`+฿${money(price)} / ชิ้น`}</strong></button>})}</div><small>ภาพอ้างอิงรูปทรงอะไหล่ สีจริงตามตัวเลือกที่ระบุ</small></>
}
export function DesignHelp(){
 return <section className={styles.help} aria-labelledby="design-help-title"><div><span className={styles.eyebrow}>ก่อนยืนยันแบบ</span><h2 id="design-help-title">ออกแบบครั้งแรก เริ่มตรงนี้</h2><p>อัปโหลดภาพ จัดตำแหน่งรู เลือกอะไหล่ แล้วดูราคาได้ทันที</p></div><div><details><summary>ต้องเตรียมไฟล์แบบไหน?</summary><p>ใช้ PNG พื้นหลังโปร่งใส หรือ JPG ขนาดไม่เกิน 15 MB ต่อไฟล์ ภาพพื้นหลังสีเดียวใช้ปุ่มลบพื้นหลังได้ ส่วนภาพฉากซับซ้อนให้เตรียม PNG โปร่งใสหรือให้กราฟิกช่วยตรวจ เก็บภาพต้นฉบับที่คมชัดที่สุดไว้ด้วย</p></details><details><summary>ขนาดภาพกับขนาดคิดราคาต่างกันอย่างไร?</summary><p>ขนาดที่กรอกคือด้านยาวของภาพก่อนเพิ่มขอบใส 1 มม. และหูห่วง ระบบคิดราคาจากด้านที่ยาวที่สุดของชิ้นงานรวม แล้วปัดขึ้นเป็นเซนติเมตรตามตารางราคา เริ่มที่ 2 ซม. ขนาดรวมจริงแสดงใต้ภาพตัวอย่าง</p></details><details><summary>พิมพ์กลับด้าน ต้องกลับภาพเองไหม?</summary><p>อัปโหลดภาพในทิศทางที่ต้องการให้ลูกค้ามองเห็นได้เลย ภาพตัวอย่างแสดงมุมมองชิ้นงานสำเร็จ ทีมผลิตจะเตรียมไฟล์พิมพ์กลับด้านสำหรับมองผ่านอะคริลิกใส งานสองด้านใช้ภาพหน้า หมึกขาวคั่น และภาพหลังพิมพ์ซ้อนบนผิวเดียวกัน</p></details><details><summary>ยืนยันแล้วผลิตทันทีไหม?</summary><p>เมื่อเปิดผ่านลิงก์ออเดอร์ คุณยืนยันส่งแบบให้กราฟิกตรวจได้ ทีมกราฟิกจะตรวจภาพ เส้นตัด และรูห่วงก่อนอนุมัติผลิต หากเปิดมาทดลองออกแบบ คุณดาวน์โหลดภาพตัวอย่างแล้วติดต่อทีมงานเพื่อเปิดออเดอร์ได้ ราคาหน้านี้ยังไม่รวม VAT และค่าส่ง</p></details></div></section>
}
