"use client";
import { useState } from "react";

type Channel={id:number;code:string;name:string;prefix:string;platform:string;active:number;sort_order:number;created_by:string;updated_at:string};
type Tier={id:number;sales_owner_id:number|null;sales_owner_name:string;tier_name:string;min_sales:number;max_sales:number|null;rate_percent:number;effective_from:string;effective_to:string;active:number;created_by_name:string;updated_at:string};
type SalesUser={id:number;display_name:string;username:string};
const money=(value:number)=>Number(value||0).toLocaleString("th-TH",{maximumFractionDigits:0});

export default function SalesSettingsManager({channels,tiers,salesUsers}:{channels:Channel[];tiers:Tier[];salesUsers:SalesUser[]}){
 const[message,setMessage]=useState("");
 async function submit(url:string,body:Record<string,unknown>){setMessage("กำลังบันทึก…");try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok)return setMessage(result.error||"บันทึกไม่สำเร็จ");setMessage("บันทึกเรียบร้อยแล้ว");setTimeout(()=>location.reload(),500)}catch{setMessage("เชื่อมต่อระบบไม่ได้ กรุณาลองอีกครั้ง")}}
 function addChannel(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void submit("/api/admin/sales-settings/channels",{action:"create",name:data.get("name"),prefix:data.get("prefix"),platform:data.get("platform")})}
 function addTier(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void submit("/api/admin/sales-settings/commissions",{action:"create",salesOwnerId:data.get("salesOwnerId")||null,tierName:data.get("tierName"),minSales:Number(data.get("minSales")),maxSales:data.get("maxSales")===""?null:Number(data.get("maxSales")),ratePercent:Number(data.get("ratePercent")),effectiveFrom:data.get("effectiveFrom"),effectiveTo:data.get("effectiveTo")})}
 return <div className="salesSettingsManager">{message&&<div className="userManagerMessage" role="status">{message}</div>}
  <section className="salesSettingCard"><header><div><span>SALES CHANNELS</span><h2>เพจและช่องทางขาย</h2><p>อักษรนำหน้าจะใช้สร้างเลขใบงาน เช่น TT-1268</p></div></header><form className="salesSettingsForm channel" onSubmit={addChannel}><label>ชื่อเพจ / ช่องทาง<input name="name" placeholder="เช่น TikTok K2STUDIO" required maxLength={80}/></label><label>แพลตฟอร์ม<input name="platform" placeholder="Facebook, LINE, TikTok" required maxLength={30}/></label><label>อักษรนำหน้า<input name="prefix" placeholder="เช่น TT" required minLength={2} maxLength={6} pattern="[A-Za-z0-9]+" autoCapitalize="characters"/></label><button>+ เพิ่มช่องทาง</button></form><div className="salesChannelList">{channels.map(channel=><article className={channel.active?"":"inactive"} key={channel.id}><strong>{channel.prefix}</strong><div><b>{channel.name}</b><small>{channel.platform} • รหัสระบบ {channel.code}</small></div><span>{channel.active?"ใช้งานอยู่":"ปิดใช้งาน"}</span><button type="button" onClick={()=>submit("/api/admin/sales-settings/channels",{action:"toggle",id:channel.id,active:channel.active?0:1})}>{channel.active?"ปิด":"เปิด"}</button></article>)}</div></section>
  <section className="salesSettingCard"><header><div><span>COMMISSION TIERS</span><h2>เรตคอมมิชชั่นแบบขั้นบันได</h2><p>คำนวณจากยอดขายสินค้า ไม่รวม VAT และค่าส่ง • เรตเฉพาะบุคคลมีสิทธิ์เหนือเรตกลาง</p></div></header><form className="salesSettingsForm commission" onSubmit={addTier}><label>ใช้กับเซลล์<select name="salesOwnerId"><option value="">เรตกลาง — ทุกคน</option>{salesUsers.map(user=><option key={user.id} value={user.id}>{user.display_name} (@{user.username})</option>)}</select></label><label>ชื่อเรต<input name="tierName" placeholder="เช่น Silver" required maxLength={60}/></label><label>ยอดเริ่มต้น<input name="minSales" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>ยอดสูงสุด<input name="maxSales" type="number" min="0" step="0.01" placeholder="ไม่จำกัด"/></label><label>คอมมิชชั่น (%)<input name="ratePercent" type="number" min="0" max="100" step="0.01" required/></label><label>เริ่มใช้<input name="effectiveFrom" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>สิ้นสุด<input name="effectiveTo" type="date"/></label><button>+ เพิ่มเรต</button></form><div className="commissionTierList">{tiers.length?tiers.map(tier=><article className={tier.active?"":"inactive"} key={tier.id}><div><span>{tier.sales_owner_name}</span><b>{tier.tier_name} • {tier.rate_percent}%</b><small>ยอด ฿{money(tier.min_sales)} – {tier.max_sales==null?"ไม่จำกัด":`฿${money(tier.max_sales)}`} • {tier.effective_from}{tier.effective_to?` ถึง ${tier.effective_to}`:" เป็นต้นไป"}</small></div><em>{tier.active?"ใช้งาน":"ปิดแล้ว"}</em>{tier.active&&<button type="button" onClick={()=>submit("/api/admin/sales-settings/commissions",{action:"close",id:tier.id})}>ปิดเรตวันนี้</button>}</article>):<p className="salesSettingsEmpty">ยังไม่มีเรตคอมมิชชั่น ระบบจะแสดง “ยังไม่ตั้งเรต” ในอันดับเซลล์</p>}</div></section>
 </div>
}
