"use client";
import { useState } from "react";
import type { Member } from "../member-auth";
import { memberFetch } from "./member-fetch";
export default function MemberGate({onVerified}:{onVerified:(member:Member)=>void}){
 const [email,setEmail]=useState(""),[challenge,setChallenge]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const data=await memberFetch<{member?:Member;challengeId:string;email:string}>("/api/member/auth",challenge?{action:"verify",challengeId:challenge,code}:{action:"start",email});if(data.member)onVerified(data.member);else{setChallenge(data.challengeId);setEmail(data.email);}}catch(e){setError(e instanceof Error?e.message:"ทำรายการไม่สำเร็จ");}finally{setBusy(false);}}
 return <form onSubmit={submit} className="memberGate"><span className="memberEyebrow">บัญชีของคุณ</span><h2>{challenge?"ตรวจอีเมลของคุณ":"ยืนยันอีเมล แล้วสั่งงานต่อ"}</h2><p>{challenge?`เราส่งรหัส 6 หลักไปที่ ${email} แล้ว` : "อีเมลใหม่จะสร้างสมาชิกให้คุณ อีเมลเดิมใช้เข้าสู่บัญชี เพื่อดูใบสั่งซื้อและติดตามงานได้ในที่เดียว"}</p>{challenge?<label>รหัสยืนยัน 6 หลัก<input autoFocus required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></label>:<label>อีเมล<input autoFocus required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}{error&&<p role="alert" className="memberError">{error}</p>}<button className="memberPrimary" disabled={busy}>{busy?"กำลังดำเนินการ…":challenge?"ยืนยันอีเมล":"ส่งรหัสยืนยัน"}</button>{challenge&&<button className="memberSecondary" type="button" disabled={busy} onClick={()=>{setChallenge("");setCode("");setError("");}}>เปลี่ยนอีเมล / ขอรหัสใหม่</button>}<small>ตะกร้าและไฟล์ที่เลือกไว้ยังอยู่ อีเมลนี้ใช้สำหรับบัญชีและการแจ้งข้อมูลใบสั่งซื้อ</small></form>;
}
