import {HARDWARE, PRICE_TABLES, SIZES} from "../pricing-config";

const fmt=(n:number|null)=>n===null?"สอบถามราคา":new Intl.NumberFormat("th-TH",{maximumFractionDigits:2}).format(n);
function Table({kind,thickness}:{kind:"retail"|"factory";thickness:"2.5"|"3"}){
  const data=PRICE_TABLES[kind];
  const awaitingOfficialPrice=kind==="factory"&&thickness==="3";
  return <div className="priceTableWrap"><div className="tableTitle"><div><span>{kind==="retail"?"ราคาขายทั่วไป":"ราคาโรงงาน"}</span><h2>อะคริลิก {thickness} มม.</h2></div><b>{kind==="retail"?"1–999 ชิ้น":"1,000+ ชิ้น"}</b></div>{awaitingOfficialPrice&&<p className="priceUnavailable">ยังไม่มีตารางราคาโรงงาน 3 มม. ที่ยืนยันแล้ว กรุณาสอบถามเจ้าหน้าที่</p>}<div className="tableScroll"><table><thead><tr><th>จำนวน / ขนาด</th>{SIZES.map(s=><th key={s}>{s} ซม.</th>)}</tr></thead><tbody>{data[thickness].map((row,i)=><tr key={data.tiers[i]}><th>{data.tiers[i]} ชิ้น</th>{row.map((p,j)=><td key={j}>{fmt(p)}</td>)}</tr>)}</tbody></table></div></div>
}
export default function PriceList(){return <main className="pricePage"><nav><a className="brand" href="/"><img src="/assets/k2sign-logo.png" alt="K2SIGN"/><span>ACRYLIC KEYCHAIN</span></a><div className="navlinks"><a href="/">หน้าแรก</a><a href="/#hardware">อะไหล่</a><a href="/#faq">คำถามที่พบบ่อย</a></div><a className="lineBtn" href="https://line.me/R/ti/p/@k2sign">LINE @k2sign</a></nav><header className="priceHero"><div><span>K2SIGN • OFFICIAL PRICE LIST</span><h1>ตารางราคา<br/><em>พวงกุญแจอะคริลิก</em></h1><p>เลือกราคาตามความหนา ขนาด และจำนวน ระบบคิดจากด้านที่ยาวที่สุดและปัดเศษขึ้น</p><div className="heroActions"><a href="/shop">เลือกสินค้าและสั่งงาน</a><a href="/#quote">คำนวณราคาออนไลน์</a><a href="/">กลับหน้าแรก</a></div></div><img src="/assets/keychain-abstract.png" alt="พวงกุญแจอะคริลิก K2SIGN"/></header><section className="priceIntro"><div><b>01</b><span>เลือกความหนา<br/>2.5 หรือ 3 มม.</span></div><div><b>02</b><span>ใช้ด้านที่ยาวที่สุด<br/>ปัดขึ้นเป็น ซม.</span></div><div><b>03</b><span>เลือกช่วงจำนวน<br/>ดูราคาต่อชิ้น</span></div></section><section className="allTables"><Table kind="retail" thickness="2.5"/><Table kind="retail" thickness="3"/><Table kind="factory" thickness="2.5"/><Table kind="factory" thickness="3"/></section><section className="addons"><div className="sectionHead"><span>ADD-ON PRICE</span><h2>ค่าพิมพ์สองหน้า</h2></div><div className="addonTables"><div><h3>ต่ำกว่า 1,000 ชิ้น</h3><p>เพิ่มต่อชิ้นตามขนาด</p><div className="miniPrices">{SIZES.map((s,i)=><span key={s}><b>{s} ซม.</b>+{PRICE_TABLES.doublePrint.retail[i]} บาท</span>)}</div></div><div><h3>ตั้งแต่ 1,000 ชิ้น</h3><p>เพิ่มต่อชิ้นตามขนาด</p><div className="miniPrices">{SIZES.map((s,i)=><span key={s}><b>{s} ซม.</b>+{PRICE_TABLES.doublePrint.factory[i]} บาท</span>)}</div></div></div></section><section className="hardwarePrices"><div className="sectionHead"><span>HARDWARE PRICE</span><h2>ราคาอะไหล่เพิ่มเติม</h2></div><div className="hardwarePriceGrid">{HARDWARE.map(h=><article key={h.code}><b>{h.code}</b><div><h3>{h.name}</h3><p>{h.price===null?"เจ้าหน้าที่ประเมินราคา":h.price===0?"รวมในราคา":`เพิ่ม ${h.price} บาท / ชิ้น`}</p></div></article>)}</div></section><section className="priceNotes"><h2>เงื่อนไขราคา</h2><ul><li>ราคาที่แสดงเป็นราคาประเมินเบื้องต้น</li><li>ราคาสุดท้ายต้องผ่านการตรวจไฟล์และยืนยันจากเจ้าหน้าที่</li><li>ไม่รวม VAT และค่าจัดส่ง</li><li>งานคละแบบคิดราคาตามจำนวนต่อแบบ</li><li>งานด่วน รูปทรงพิเศษ ขนาดเกิน 10 ซม. และแพ็กเกจพิเศษต้องประเมินเพิ่มเติม</li></ul><a href="/#quote">คำนวณราคาสเปกของคุณ →</a></section><footer><div className="footerBrand"><img src="/assets/k2sign-logo.png" alt="K2SIGN"/><p>เปลี่ยนไอเดียของคุณ<br/>ให้เป็นของจริงที่จับต้องได้</p></div><div><b>ติดต่อเรา</b><a href="https://line.me/R/ti/p/@k2sign">LINE @k2sign</a><a href="tel:0659895887">065-989-5887</a></div><div><b>สำนักงาน</b><p>K2SIGN MEDIA CO., LTD.<br/>สำนักงานใหญ่ พระราม 9 กรุงเทพฯ</p></div></footer></main>}
