import { env } from "cloudflare:workers";
import { notFound } from "next/navigation";
import { can, canManageOrderFinance, canManageOrderNumber, canManagePricing, canViewOrderFinance, canViewOrderSlips, requireStaff } from "../../../staff-auth";
import FinancialForm from "../../FinancialForm";
import DesignUploadForm from "../../DesignUploadForm";
import PaymentSlipForm from "../../PaymentSlipForm";
import PricingEditor from "../../PricingEditor";
import OrderEditForm from "../../OrderEditForm";
import ProductionFileLinkForm from "../../ProductionFileLinkForm";
import AdminLiveSync from "../../AdminLiveSync";
import { publicOrderStatus, statusLabels, thaiPhotoTimestamp } from "../../../order-status";
import QrCodeImage from "../../../QrCodeImage";
import WorkOrderPlanningPanel from "../../WorkOrderPlanningPanel";
import CustomerShareMessage from "../../../CustomerShareMessage";
import StatusForm from "../../StatusForm";
import QuickProgressPhotoUpload from "../../QuickProgressPhotoUpload";
import { parseSlipAnswer, slipAmountStatus } from "../../../payment-slip-analysis";
import GraphicClaimButton from "../../GraphicClaimButton";
import ShipmentManager from "../../ShipmentManager";
import { canManageShipments, listShipments } from "../../../shipments";
import { VAT_POLICY_MODES, orderTaxCollectionLabel } from "../../../vat-collection-policy.mjs";
import { hardwareImagePath } from "../../../pricing-config";
import MemberOrderAttachments from "../../MemberOrderAttachments";

export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("th-TH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);

export default async function OrderDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireStaff(`/admin/orders/${id}`);
  const database = (env as unknown as { DB: D1Database }).DB;
  const order = await database.prepare("SELECT * FROM orders WHERE id=? LIMIT 1").bind(Number(id)).first<Record<string, string | number>>();
  if (!order) notFound();
  const orderId = Number(order.id);
  const shipments = await listShipments(database, orderId);
  const canSeeFinance = canViewOrderFinance(user, Number(order.sales_owner_id || 0));
  const hasVatPolicy = VAT_POLICY_MODES.includes(String(order.vat_policy_mode || ""));
  const orderVatMetadata = { vatPolicyMode: String(order.vat_policy_mode || ""), taxInvoiceRequested: Number(order.tax_invoice_requested) === 1 };
  const canManageFinance = canManageOrderFinance(user, Number(order.sales_owner_id || 0));
  const canSeeSlips = canViewOrderSlips(user, Number(order.sales_owner_id || 0));
  const publicSiteUrl = process.env.PUBLIC_SITE_URL ?? "https://order.k2group.site";
  const publicToken = String(order.public_token || "");
  const trackingUrl = `${publicSiteUrl}/track/${publicToken}`;
  const history = (await database.prepare("SELECT status,note,created_at FROM order_status_history WHERE order_id=? ORDER BY id DESC").bind(orderId).all<Record<string, string>>()).results;
  const designs = (await database.prepare("SELECT id,version_no,file_name,scale_file_name,mockup_file_name,note,status,created_by,created_at,customer_note,responded_by,responded_at FROM design_versions WHERE order_id=? ORDER BY version_no DESC").bind(orderId).all<Record<string, string | number>>()).results;
  const designAssets = (await database.prepare("SELECT da.id,da.design_version_id,da.order_item_id,da.asset_type,da.file_name,da.caption,da.sort_order,d.version_no,d.status AS design_status FROM design_assets da JOIN design_versions d ON d.id=da.design_version_id WHERE d.order_id=? ORDER BY d.version_no DESC,CASE da.asset_type WHEN 'scale' THEN 0 ELSE 1 END,da.sort_order,da.id").bind(orderId).all<Record<string, string | number>>()).results;
  const items = (await database.prepare("SELECT * FROM order_items WHERE order_id=? ORDER BY line_no").bind(orderId).all<Record<string, string | number>>()).results;
  const adjustments = (await database.prepare("SELECT id,label,amount FROM order_adjustments WHERE order_id=? ORDER BY id").bind(orderId).all<Record<string, string | number>>()).results;
  const paymentReceipts = canSeeSlips ? (await database.prepare("SELECT id,amount,file_name,file_key,created_by_name,created_at FROM order_payment_receipts WHERE order_id=? ORDER BY id ASC").bind(orderId).all<Record<string, string | number>>()).results : [];
  const paymentAnalyses = canSeeSlips ? (await database.prepare("SELECT receipt_id,status,expected_amount,detected_amount,transaction_date,transaction_time,reference_no,sender_name,receiver_name,confidence,note,raw_result,error_message,updated_at FROM payment_slip_analyses WHERE order_id=? ORDER BY id DESC").bind(orderId).all<Record<string, string | number | null>>()).results : [];
  const audits = (await database.prepare("SELECT display_name,username,action,details,created_at FROM audit_logs WHERE order_id=? ORDER BY id DESC LIMIT 50").bind(orderId).all<Record<string, string>>()).results;
  const progressPhotos = (await database.prepare("SELECT id,status,file_name,caption,created_by_name,created_at FROM order_progress_photos WHERE order_id=? ORDER BY id ASC").bind(orderId).all<Record<string, string | number>>()).results;
  const workOrder = await database.prepare("SELECT * FROM work_orders WHERE order_id=? LIMIT 1").bind(orderId).first<Record<string, string | number>>();
  const machines = (await database.prepare("SELECT id,code,name FROM machines WHERE active=1 ORDER BY name").all<{ id: number; code: string; name: string }>()).results;
  const salesUsers = (await database.prepare("SELECT u.id,u.display_name,u.username FROM staff_users u WHERE (u.active=1 AND (u.role IN ('admin','production_manager','sales','sales_manager') OR EXISTS (SELECT 1 FROM staff_user_teams t WHERE t.user_id=u.id AND t.team_code='sale'))) OR u.id=? ORDER BY u.active DESC,u.display_name,u.username").bind(Number(order.sales_owner_id||0)).all<{id:number;display_name:string;username:string}>()).results;
  const salesChannels = (await database.prepare("SELECT code,name,prefix,active FROM sales_channels WHERE active=1 OR code=? ORDER BY active DESC,sort_order,name").bind(String(order.contact_channel||"")).all<{code:string;name:string;prefix:string;active:number}>()).results;
  const processes = (await database.prepare("SELECT id,code,name FROM production_processes WHERE active=1 ORDER BY sequence_no,name").all<{ id: number; code: string; name: string }>()).results;
  const schedules = workOrder ? (await database.prepare("SELECT ps.id,ps.production_date,ps.estimated_minutes,ps.quantity,m.name AS machine_name,COALESCE(p.name,'') AS process_name FROM production_schedule ps JOIN machines m ON m.id=ps.machine_id LEFT JOIN production_processes p ON p.id=ps.process_id WHERE ps.work_order_id=? AND ps.status<>'cancelled' ORDER BY ps.production_date,ps.sequence_no,ps.id").bind(Number(workOrder.id)).all<{ id: number; production_date: string; estimated_minutes: number; quantity: number; machine_name: string; process_name: string }>()).results : [];
  const shippingFee = Number(order.shipping_fee || 0);
  const paidAmount = Number(order.deposit_amount || 0);
  const payableTotal = Number(order.estimated_total) + shippingFee;
  const outstanding = Math.max(0, payableTotal - paidAmount);
  const hasPaymentSlip = Boolean(order.payment_slip_key);
  const legacySlipIsReceipt = hasPaymentSlip && paymentReceipts.some(receipt => String(receipt.file_key) === String(order.payment_slip_key));
  const showLegacyInstallment = hasPaymentSlip && !legacySlipIsReceipt;
  const receiptTotal = paymentReceipts.reduce((sum, receipt) => sum + Number(receipt.amount || 0), 0);
  const legacyPaymentAmount = showLegacyInstallment ? Math.max(0, paidAmount - receiptTotal) : 0;
  const paymentEvidence = hasPaymentSlip || paymentReceipts.length > 0;
  const paymentStatusText = outstanding <= 0.009
    ? paymentEvidence ? "✓ ชำระเต็มจำนวน" : "รอสลิปยืนยันยอด"
    : paidAmount > 0.009 ? canSeeFinance ? `มัดจำแล้ว • ค้าง ฿${money(outstanding)}` : "มียอดค้างชำระ" : canSeeFinance ? `ยังไม่ชำระ • ค้าง ฿${money(outstanding)}` : "ยังไม่ชำระ";
  const latestDesign = designs[0];
  const graphicCanClaim = user.role === "admin" || user.role === "production_manager" || user.role === "graphic" || user.teams.includes("graphic");
  const productionReleased = String(order.order_status) === "in_production" || Boolean(order.production_released_at);
  const productionQueued = Boolean(workOrder) && String(workOrder?.status || "") !== "draft";
  const workflowStage = publicOrderStatus(String(order.order_status));
  const hasArtworkPreview = Boolean(order.artwork_key) && String(order.artwork_type || "").startsWith("image/");
  const savedImageCount = (hasArtworkPreview ? 1 : 0) + designAssets.length + progressPhotos.length;
  const channelLabels: Record<string, string> = Object.fromEntries(salesChannels.map(channel=>[channel.code,`${channel.prefix} — ${channel.name}`]));channelLabels.line="LINE @k2sign (ข้อมูลเดิม)";channelLabels.other="อื่น ๆ (ข้อมูลเดิม)";
  const fileMethodLabels: Record<string, string> = { upload: "อัปโหลดในเว็บไซต์", google_drive: "Google Drive", email: "ส่งทางอีเมล" };
  const packagingLabels: Record<string, string> = { standard: "ซองใสมาตรฐาน", none: "ไม่รับแพ็ก", backing: "การ์ดรองหลัง", custom: "แพ็กเกจสั่งทำพิเศษ", custom_order: "ระบุตามรายละเอียดงาน" };
  const itemFields = items.flatMap(item => String(item.product_type) === "custom" ? [[`รายการ ${item.line_no} — งานสั่งทำ`, String(item.item_name)], [`รายการ ${item.line_no} — รายละเอียด`, String(item.item_description || "-")], [`รายการ ${item.line_no} — จำนวน`, `${Number(item.quantity).toLocaleString()} หน่วย`], ...(canSeeFinance ? [[`รายการ ${item.line_no} — ราคา`, `฿${Number(item.unit_price).toLocaleString()}/หน่วย • รวม ฿${Number(item.line_total).toLocaleString()}`]] : [])] : [[`รายการ ${item.line_no} — ขนาด`, `${item.width_cm} × ${item.height_cm} ซม. • ${item.thickness_mm} มม.`], [`รายการ ${item.line_no} — จำนวน/พิมพ์`, `${Number(item.quantity).toLocaleString()} ชิ้น • ${item.print_sides} ด้าน`], [`รายการ ${item.line_no} — อะไหล่`, `${item.hardware_code} — ${item.hardware_name} ${item.hardware_color || ""}`], ...(canSeeFinance ? [[`รายการ ${item.line_no} — ราคา`, `฿${Number(item.unit_price).toLocaleString()}/ชิ้น • รวม ฿${Number(item.line_total).toLocaleString()}`]] : [])]);
  const financialFields = canSeeFinance ? [["ราคาเฉลี่ยต่อหน่วย", `฿${order.estimated_unit_price}`], ["รวมสินค้าและรายการเสริม", `฿${Number(order.estimated_subtotal || order.estimated_total).toLocaleString()}`], ["ค่าจัดส่ง", `฿${shippingFee.toLocaleString()}`], ["VAT ที่บวกเพิ่ม 7%", Number(order.vat_applied) === 1 ? `฿${Number(order.vat_amount).toLocaleString()}` : hasVatPolicy ? "ไม่บวกเพิ่ม — ฝ่ายบัญชีแยก" : "ไม่ได้บันทึก VAT เพิ่ม"], ["ยอดรวมสุทธิ", `฿${payableTotal.toLocaleString()}`], ["รับชำระแล้ว", `฿${paidAmount.toLocaleString()}`], ["ยอดค้างชำระ", `฿${outstanding.toLocaleString()}`]] : [];
  const fields = [["ลูกค้า", order.contact_name], ["โทรศัพท์", order.phone], ["LINE ID", order.line_id || "-"], ["อีเมล", order.email || "-"], ["เซลล์ผู้รับผิดชอบ", order.sales_owner_name || "ยังไม่ระบุเซลล์"], ["ช่องทางที่ติดต่อ", channelLabels[String(order.contact_channel)] || "-"], ["ชื่อ Facebook / LINE", order.social_contact_name || "-"], ["ช่องทางส่งไฟล์", fileMethodLabels[String(order.file_delivery_method)] || "-"], ["ลิงก์ Google Drive", order.external_file_url || "-"], ["อีเมล/หมายเหตุไฟล์", order.file_delivery_note || "-"], ["ที่อยู่จัดส่ง", order.address || "-"], ["จังหวัด", order.province || "-"], ["วันส่งงาน", order.requested_date || "-"], ["โหมดเร่งคิว", String(order.rush_mode) === "urgent" ? "เร่งด่วน" : "ปกติ"], ["จำนวนวันที่เร่ง", `${Number(order.requested_speed_days || 0).toLocaleString()} วัน`], ["แพ็กเกจเร่งคิว", String(order.delivery_tier || "-") || "-"], ["ค่าบริการเร่ง", `฿${Number(order.rush_fee || 0).toLocaleString()}`], ["หมายเหตุเร่งคิว", order.rush_note || "-"], ...itemFields, ["จำนวนรวม", `${Number(order.quantity).toLocaleString()} หน่วย`], ...financialFields];
  const normalizedPaymentAnalyses = paymentAnalyses.map(item => {
    const expectedAmount = Number(item.expected_amount || 0);
    const storedAmount = String(item.detected_amount || "") ? Number(item.detected_amount) : null;
    const recovered = storedAmount === null && item.raw_result ? parseSlipAnswer(String(item.raw_result)) : null;
    const detectedAmount = storedAmount ?? recovered?.amount ?? null;
    const confidence = String(recovered?.confidence || item.confidence || "");
    const recoveredStatus = detectedAmount !== null && confidence !== "low" ? slipAmountStatus(detectedAmount, expectedAmount) : String(item.status);
    return { receiptId: item.receipt_id === null ? null : Number(item.receipt_id), status: recoveredStatus, expectedAmount, detectedAmount, transactionDate: String(item.transaction_date || recovered?.transactionDate || ""), transactionTime: String(item.transaction_time || recovered?.transactionTime || ""), referenceNo: String(item.reference_no || recovered?.referenceNo || ""), senderName: String(item.sender_name || recovered?.senderName || ""), receiverName: String(item.receiver_name || recovered?.receiverName || ""), confidence, note: String(recovered ? recovered.note : item.note || ""), errorMessage: String(item.error_message || ""), updatedAt: String(item.updated_at || "") };
  });

  return <main className="adminDetail">
    <p><a href={`/admin/orders/${orderId}/customer-designs`}>แบบที่ลูกค้าจัดเอง / ลิงก์ออกแบบพวงกุญแจ →</a></p>
    <header><div><a href="/admin">← กลับหน้ารายการ</a><span>JOB ORDER</span><h1>{order.order_number}</h1><p>สร้างเมื่อ {String(order.created_at)}</p></div><div className="staffHeaderUser"><AdminLiveSync/><b>{user.displayName}</b><span>@{user.username}</span><a href="/api/staff/logout">ออกจากระบบ</a></div></header>

    {canSeeFinance && hasVatPolicy && <section className="orderTaxNotice"><strong>{orderTaxCollectionLabel(order)}</strong><p>{orderVatMetadata.taxInvoiceRequested ? "ลูกค้าขอใบกำกับภาษีเต็มรูป" : "ลูกค้าไม่ขอใบกำกับภาษีเต็มรูป"} · เก็บโหมดตามวันที่สร้างใบงาน ไม่เปลี่ยนตามการตั้งค่าใหม่</p><small>ข้อมูลการเรียกเก็บกับลูกค้า ไม่ใช่รายงานยื่นภาษี รายการไม่บวกเพิ่มให้ฝ่ายบัญชีแยกภาษีต่อ</small></section>}
    <section className="adminStatusCommand"><div><span>JOB STATUS</span><h2>เปลี่ยนสถานะงาน</h2><p>กดปุ่มใหญ่เพื่อไปขั้นตอนถัดไป ระบบจะป้องกันการปิดงานหากยังมียอดค้าง</p></div><StatusForm key={String(order.order_status)} orderId={orderId} publicToken={publicToken} initialStatus={String(order.order_status)} outstandingAmount={outstanding} hasPaymentEvidence={paymentEvidence}/></section>

    {(canManageFinance||canSeeSlips)&&<section className={`paymentQuickAccess ${outstanding > 0.009 || !paymentEvidence ? "needsAttention" : "isComplete"}`} id="payment-tools"><header><div><span>PAYMENT</span><h2>{canManageFinance ? "บันทึกรับชำระ / แนบสลิป" : "ข้อมูลการชำระเงินและสลิป"}</h2><p>{canManageFinance ? "เพิ่มการชำระงวดถัดไปได้ตรงนี้ ไม่ต้องเปิดเมนูอื่น" : "ตรวจสอบยอดและประวัติสลิปของใบงานนี้"}</p></div><b>{paymentStatusText}</b></header><PaymentSlipForm orderId={orderId} totalAmount={payableTotal} paidAmount={paidAmount} hasLegacySlip={showLegacyInstallment} legacyAmount={legacyPaymentAmount} receipts={paymentReceipts.map(receipt => ({ id: Number(receipt.id), amount: Number(receipt.amount), fileName: String(receipt.file_name), createdBy: String(receipt.created_by_name), createdAt: String(receipt.created_at) }))} analyses={normalizedPaymentAnalyses} canManage={canManageFinance}/></section>}
    {canSeeFinance&&!canManageFinance&&!canSeeSlips&&<section className="paymentAccessNotice"><div><span>PAYMENT ACCESS</span><b>บัญชีนี้ยังไม่มีสิทธิ์แนบสลิปงวดถัดไป</b><small>ให้ผู้ดูแลระบบเพิ่มสิทธิ์ “บันทึกและแก้ไขการรับชำระ” และ “ดูและดาวน์โหลดสลิป” ในเมนูผู้ใช้งาน</small></div><strong>ติดต่อผู้ดูแลระบบ</strong></section>}

    {!latestDesign && !["in_production","waiting_for_packing","packing","ready_to_ship","shipped","completed","cancelled"].includes(String(order.order_status)) && <section className="graphicClaimPanel"><div><span>GRAPHIC OWNER</span><h2>ผู้รับผิดชอบงานกราฟิก</h2></div><GraphicClaimButton orderId={orderId} claimedBy={String(order.graphic_claimed_by_name || "")} claimedAt={String(order.graphic_claimed_at || "")} canClaim={graphicCanClaim}/></section>}

    {String(order.contact_channel)==="customer_web"&&<MemberOrderAttachments database={database} orderId={orderId}/>}
    <section className="orderEssentialCard">
      <header><div><span>IMPORTANT ORDER INFO</span><h2>ข้อมูลสำคัญที่ต้องใช้ทำงาน</h2></div><b className={outstanding > 0.009 || !paymentEvidence ? "paymentDueBadge" : "paymentPaidBadge"}>{paymentStatusText}</b></header>
      <div className="orderEssentialStats"><div><span>ลูกค้า</span><b>{String(order.contact_name)}</b><small>{String(order.phone)}</small></div><div><span>เซลล์ / ช่องทาง</span><b>{String(order.sales_owner_name || "ยังไม่ระบุเซลล์")}</b><small>{channelLabels[String(order.contact_channel)] || "ยังไม่ระบุช่องทาง"}</small></div><div><span>กำหนดส่ง</span><b>{String(order.requested_date || "ยังไม่กำหนด")}</b><small>{String(order.province || "-")}</small></div><div><span>แบบเร่งคิว</span><b>{String(order.rush_mode) === "urgent" ? "เร่งด่วน" : "ปกติ"}</b><small>{Number(order.requested_speed_days || 0)} วัน / ค่าบริการ {money(Number(order.rush_fee || 0))} บาท</small></div><div><span>จำนวนรวม</span><b>{Number(order.quantity).toLocaleString("th-TH")} หน่วย</b><small>{items.length} รายการ</small></div>{canSeeFinance?<div><span>ยอดสุทธิ / รับแล้ว</span><b>฿{money(payableTotal)}</b><small>รับแล้ว ฿{money(paidAmount)}</small></div>:<div><span>สถานะการชำระ</span><b>{outstanding<=0.009?"ชำระครบ":"มียอดค้าง"}</b><small>ซ่อนจำนวนเงินตามสิทธิ์</small></div>}</div>
      <div className="orderProductSummary">{items.map(item => { const isCustom = String(item.product_type) === "custom"; const lineNo = String(item.line_no); const itemAssets = designAssets.filter(asset => Number(asset.order_item_id) === Number(item.id) || (items.length === 1 && !asset.order_item_id)); const latestItemVersion = itemAssets[0]?.version_no; const pairedArtwork = itemAssets.filter(asset => String(asset.version_no) === String(latestItemVersion)).slice(0, 2); return <article key={String(item.id)} className="visualJobItem">
        <div className="visualJobItemHead"><span>รายการ {lineNo}</span><b>{Number(item.quantity).toLocaleString("th-TH")} {isCustom ? "หน่วย" : "ชิ้น"}</b></div>
        <div className="visualJobItemBody">
          <div className={`visualJobMedia itemAssetPair ${isCustom ? "custom" : ""}`}>
            <section className="jobArtworkPane"><header><span>ภาพแบบรายการนี้</span>{latestItemVersion && <b>V{String(latestItemVersion)}</b>}</header>{pairedArtwork.length ? <div className="jobArtworkPreviews">{pairedArtwork.map(asset => <a key={String(asset.id)} href={`/api/orders/${publicToken}/design?asset=${asset.id}`} target="_blank" rel="noreferrer"><img src={`/api/orders/${publicToken}/design?asset=${asset.id}`} alt={`ภาพแบบรายการ ${lineNo} เวอร์ชัน ${String(asset.version_no)}`} loading="lazy"/><small>{String(asset.asset_type) === "scale" ? "ภาพสเกล" : "ภาพม็อกอัป"}</small></a>)}</div> : <div className="jobArtworkEmpty">{isCustom && <i>CUSTOM</i>}<b>ยังไม่มีภาพแบบรายการนี้</b><small>เมื่อกราฟิกอัปโหลด ภาพจะจับคู่กับรายการนี้อัตโนมัติ</small></div>}</section>
            {!isCustom && <section className="jobHardwarePane"><header><span>อะไหล่รายการนี้</span><b>{String(item.hardware_code)}</b></header><img src={hardwareImagePath(String(item.hardware_code), String(item.hardware_name))} alt={`อะไหล่ ${String(item.hardware_code)} ของรายการ ${lineNo}`}/><small>{String(item.hardware_name)} · {String(item.hardware_color || "ไม่ระบุสี")}</small></section>}
          </div>
          <div className="visualJobContent"><h3>{String(item.item_name || "พวงกุญแจอะคริลิก")}</h3>{isCustom ? <p>{String(item.item_description || "งานสั่งทำอื่น ๆ")}</p> : <>
            <div className="criticalSpecChips"><b><small>ขนาด</small>{String(item.width_cm)} × {String(item.height_cm)} ซม.</b><b><small>ความหนา</small>{String(item.thickness_mm)} มม.</b><b><small>การพิมพ์</small>{String(item.print_sides)} ด้าน</b></div>
            <div className="hardwarePair"><span>อะไหล่ {String(item.hardware_code)}</span><strong>{String(item.hardware_name)}</strong><small>{String(item.hardware_color || "ไม่ระบุสี")}</small></div>
          </>}<div className="jobPackaging"><span>แพ็กเกจ</span><b>{packagingLabels[String(item.packaging_type)] || String(item.packaging_type || "ยังไม่ระบุ")}</b></div></div>
        </div>
        <footer><span>จุดห้ามพลาด</span><b>{isCustom ? "ตรวจรายละเอียดงานและจำนวนก่อนออกแบบ" : `${String(item.thickness_mm)} มม. • พิมพ์ ${String(item.print_sides)} ด้าน • อะไหล่ ${String(item.hardware_code)} ${String(item.hardware_color || "")}`}</b></footer>
      </article>; })}</div>
    </section>

    <ShipmentManager orderId={orderId} orderCode={String(order.order_number)} shipments={shipments} canManage={canManageShipments(user)}/>
    {publicToken && <QuickProgressPhotoUpload token={publicToken} initialStatus={String(order.order_status)}/>}
    {publicToken && <section className="adminSavedImageGallery adminSavedImageGalleryPrimary"><header><div><span>ORDER IMAGE GALLERY</span><h2>ภาพที่บันทึกในใบงาน</h2><p>ทีมงานทุกฝ่ายที่เข้าสู่ระบบจะเห็นภาพต้นฉบับ แบบ และภาพอัปเดตทุกขั้นตอนอยู่รวมกันตรงนี้</p></div><b>{savedImageCount} ภาพ</b></header>{savedImageCount ? <div className="adminSavedImageGrid">
      {hasArtworkPreview && <figure><a href={`/api/orders/${publicToken}/artwork`} target="_blank" rel="noreferrer"><img src={`/api/orders/${publicToken}/artwork`} alt={`ภาพต้นฉบับ ${String(order.order_number)}`}/></a><figcaption><b>ภาพต้นฉบับจากลูกค้า</b><span>{String(order.artwork_name || "ไฟล์งานลูกค้า")}</span></figcaption></figure>}
      {designAssets.map((asset, index) => <figure key={`design-${asset.id}`}><a href={`/api/orders/${publicToken}/design?asset=${asset.id}`} target="_blank" rel="noreferrer"><img src={`/api/orders/${publicToken}/design?asset=${asset.id}`} alt={`${String(asset.asset_type) === "scale" ? "ภาพแบบมีสเกล" : "ภาพม็อกอัป"} ${String(order.order_number)}`} loading={index < 2 ? "eager" : "lazy"}/></a><figcaption><b>V{String(asset.version_no)} • {String(asset.asset_type) === "scale" ? "ภาพแบบมีสเกล" : "ภาพม็อกอัป"}</b><span>{String(asset.caption || asset.file_name)}</span></figcaption></figure>)}
      {progressPhotos.map(photo => { const stage = publicOrderStatus(String(photo.status)); return <figure key={`progress-${photo.id}`}><a href={`/api/orders/${publicToken}/progress?photo=${photo.id}`} target="_blank" rel="noreferrer"><img src={`/api/orders/${publicToken}/progress?photo=${photo.id}`} alt={`ภาพความคืบหน้า ${statusLabels[stage]}`} loading="lazy"/><span className="photoCaptureStamp"><b>ถ่ายโดย {String(photo.created_by_name || "ทีม K2SIGN")}</b><small>{thaiPhotoTimestamp(photo.created_at)}</small></span></a><figcaption><b>{String(photo.caption || statusLabels[stage] || "ภาพความคืบหน้า")}</b><span>{statusLabels[stage]} • {thaiPhotoTimestamp(photo.created_at)} • {String(photo.created_by_name || "ทีม K2SIGN")}</span></figcaption></figure>; })}
    </div> : <div className="adminSavedImageEmpty"><b>ยังไม่มีภาพในใบงานนี้</b><span>เมื่อแนบภาพหรือถ่ายรูป ระบบจะแสดงตรงนี้ทันที</span></div>}</section>}

    <section className="adminDocumentBar"><div><b>{productionQueued ? "ใบงานเข้าสู่ไลน์ผลิตแล้ว" : "ลิงก์ลูกค้าพร้อมใช้งาน"}</b><span>{productionQueued ? "ปฏิทินและหน้าจอฝ่ายผลิตใช้ข้อมูลชุดเดียวกัน" : "ส่งลิงก์นี้ให้ลูกค้าและใช้ลิงก์เดิมตลอดงาน"}</span></div>{publicToken && <QrCodeImage value={trackingUrl} width={300} alt={`QR ${order.order_number}`}/>}<div className="adminDocumentActions"><a className="primaryDocumentAction" href={`${publicSiteUrl}/order/${publicToken}?staff=1`} target="_blank" rel="noreferrer"><span>PRINT ORDER</span><b>เปิด / พิมพ์ใบสั่งงาน</b><small>พิมพ์หรือบันทึก PDF แล้วส่งผลิตและเข้าปฏิทินอัตโนมัติ</small><i>↗</i></a><a className="secondaryDocumentAction" href={`${publicSiteUrl}/order/${publicToken}?mode=production&staff=1`} target="_blank" rel="noreferrer">เปิดใบงานฝ่ายผลิต ↗</a><a className="secondaryDocumentAction" href={`${publicSiteUrl}/order/${publicToken}`} target="_blank" rel="noreferrer">เปิดฉบับลูกค้า ↗</a><a className="textDocumentAction" href={`${publicSiteUrl}/track/${publicToken}`} target="_blank" rel="noreferrer">ติดตามสถานะ ↗</a></div></section>

    {publicToken && <div id="customer-tools"><CustomerShareMessage orderNumber={String(order.order_number)} trackingUrl={trackingUrl}/></div>}

    <section className="orderToolStack" aria-labelledby="order-tools-title">
      <header className="orderToolStackHeader"><div><span>WORKSPACE</span><h2 id="order-tools-title">ศูนย์จัดการใบงาน</h2><p>เลือกงานที่ต้องทำจากการ์ด กดครั้งเดียวเพื่อเปิดเครื่องมือ</p></div><b>เครื่องมือหลัก</b></header>
      <div className="orderToolGrid orderToolPrimaryGrid">
      <details className="orderToolDisclosure orderToolPrimary designTool" id="design-tools"><summary><span><em>กราฟิก</em><b>ส่งแบบให้ลูกค้าอนุมัติ</b><small>{designs.length ? `มีแบบแล้ว ${designs.length} เวอร์ชัน` : "อัปโหลดภาพแบบให้ลูกค้าตรวจ"}</small></span><i>เปิดใช้งาน</i></summary><div className="orderToolBody"><DesignUploadForm orderId={orderId} items={items.map(item => ({ id: Number(item.id), lineNo: Number(item.line_no), name: String(item.item_name || `รายการ ${item.line_no}`) }))}/>{latestDesign && String(latestDesign.status) === "pending" && <CustomerShareMessage orderNumber={String(order.order_number)} trackingUrl={trackingUrl} phase="design" designVersion={Number(latestDesign.version_no)}/>} {designs.length > 0 && <details className="nestedHistory"><summary>ดูแบบทั้งหมด {designs.length} เวอร์ชัน</summary><ol className="designVersionList">{designs.map(design => <li key={String(design.id)}><div><b>V{String(design.version_no)} • {String(design.status)}</b><small>{String(design.created_at)} • {String(design.created_by)}</small></div>{designAssets.filter(asset => Number(asset.design_version_id) === Number(design.id)).map((asset, index) => { const linkedItem = items.find(item => Number(item.id) === Number(asset.order_item_id)); return <span key={`${asset.asset_type}-${index}`}>รายการ {String(linkedItem?.line_no || "เดิม")} • {String(asset.asset_type) === "scale" ? "ภาพสเกล" : "ภาพม็อกอัป"} {Number(asset.sort_order)}: {String(asset.file_name)}{asset.caption ? ` • ${String(asset.caption)}` : ""}</span>; })}{design.note && <p>{String(design.note)}</p>}{design.responded_by && <p>ลูกค้าเซ็นยืนยัน: {String(design.responded_by)} • {String(design.responded_at || "")}</p>}</li>)}</ol></details>}</div></details>
      <details className="orderToolDisclosure orderToolPrimary productionTool" id="production-file-tools"><summary><span><em>ฝ่ายผลิต</em><b>ไฟล์พร้อมผลิต</b><small>{order.production_file_url ? "พร้อมแล้ว • มีลิงก์ Google Drive" : "ยังไม่มีลิงก์ไฟล์พร้อมผลิต"}</small></span><i>เปิดใช้งาน</i></summary><div className="orderToolBody"><ProductionFileLinkForm orderId={orderId} initialUrl={String(order.production_file_url || "")} initialNote={String(order.production_file_note || "")} updatedBy={String(order.production_file_updated_by || "")} updatedAt={String(order.production_file_updated_at || "")}/></div></details>
      <details className="orderToolDisclosure orderToolPrimary planningTool" id="planning-tools"><summary><span><em>แผนงาน</em><b>วางแผนผลิตและปฏิทิน</b><small>{schedules.length ? `จัดคิวแล้ว ${schedules.length} รายการ` : "ยังไม่ได้จัดคิวผลิต"}</small></span><i>เปิดใช้งาน</i></summary><div className="orderToolBody"><WorkOrderPlanningPanel orderId={orderId} workOrder={workOrder || null} machines={machines} processes={processes} schedules={schedules} canCreate={can(user.role, "work_orders:create")} canSchedule={can(user.role, "production:schedule")} canOverride={can(user.role, "capacity:override")} canManageQueue={can(user.role, "queue:manage")}/><section className="workflowOverviewCard"><h2>สถานะหลักของใบงาน</h2><ol>{([['received', 'รับงาน'], ['design_sent', 'ส่งแบบ'], ['production', 'ส่งผลิต'], ['packing', 'แพ็ก'], ['completed', 'เสร็จสมบูรณ์']] as const).map(([key, label], index) => { const activeIndex = ['received', 'design_sent', 'production', 'packing', 'completed'].indexOf(workflowStage); return <li className={index <= activeIndex ? "done" : ""} key={key}><i>{index < activeIndex ? '✓' : index + 1}</i><b>{label}</b></li>; })}</ol><p>ทีมงานทุกฝ่ายสามารถอัปเดตขั้นตอนต่อไปได้ทันที ส่วนขั้นตอนพร้อมส่ง ส่งแล้ว และเสร็จสมบูรณ์จะเปิดเมื่อชำระครบ</p>{productionReleased && order.production_released_by && <small>ส่งผลิตโดย {String(order.production_released_by)} • {String(order.production_released_at || "")}</small>}</section></div></details>
      <details className="orderToolDisclosure orderToolPrimary editTool" id="order-edit-tools"><summary><span><em>ข้อมูลใบงาน</em><b>แก้ไขข้อมูลคำสั่งผลิต</b><small>ลูกค้า สินค้า เซลล์ กำหนดส่ง และเลขใบงาน</small></span><i>เปิดใช้งาน</i></summary><div className="orderToolBody"><OrderEditForm orderId={orderId} canEditPrice={canManagePricing(user)} canEditOrderNumber={canManageOrderNumber(user.role)} salesUsers={salesUsers.map(item=>({id:Number(item.id),name:String(item.display_name),username:String(item.username)}))} salesChannels={salesChannels.map(item=>({code:String(item.code),name:String(item.name),prefix:String(item.prefix),active:Number(item.active)}))} order={{ ...orderVatMetadata, orderNumber: String(order.order_number), contactName: String(order.contact_name), phone: String(order.phone), lineId: String(order.line_id || ""), email: String(order.email || ""), contactChannel: String(order.contact_channel || "other"), socialContactName: String(order.social_contact_name || ""), salesOwnerId:Number(order.sales_owner_id||0), fileDeliveryMethod: String(order.file_delivery_method || "upload"), externalFileUrl: String(order.external_file_url || ""), fileDeliveryNote: String(order.file_delivery_note || ""), address: String(order.address || ""), province: String(order.province || ""), requestedDate: String(order.requested_date || ""), vatApplied: Number(order.vat_applied) === 1, rushMode: String(order.rush_mode || "normal"), requestedSpeedDays:Number(order.requested_speed_days || 0), deliveryTier:String(order.delivery_tier || ""), rushFee:String(order.rush_fee || "0"), rushNote:String(order.rush_note || "") }} items={items.map(item => ({ id: Number(item.id), lineNo: Number(item.line_no), productType: String(item.product_type || "acrylic_keychain"), itemName: String(item.item_name || `รายการ ${item.line_no}`), description: String(item.item_description || ""), thickness: String(item.thickness_mm), width: Number(item.width_cm), height: Number(item.height_cm), quantity: Number(item.quantity), sides: Number(item.print_sides), hardwareCode: String(item.hardware_code), hardwareName: String(item.hardware_name), hardwareColor: String(item.hardware_color || ""), packaging: String(item.packaging_type) }))}/><dl className="orderFullDetails">{fields.map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{String(value)}</dd></div>)}</dl></div></details>
      </div>

      <header className="orderToolSubHeader"><div><span>MORE DETAILS</span><h3>ข้อมูลเพิ่มเติม</h3></div><p>ใช้เมื่อต้องตรวจสอบหรือแก้ไขข้อมูลเฉพาะส่วน</p></header>
      <div className="orderToolGrid orderToolSecondaryGrid">
      {canManagePricing(user)&&<details className="orderToolDisclosure orderToolSecondary" id="pricing-tools"><summary><span><b>ราคาและค่าจัดส่ง</b><small>ส่วนลด VAT รายการเสริม และค่าจัดส่ง</small></span><i>ดู / แก้ไข</i></summary><div className="orderToolBody toolTwoColumns"><section className="pricingAdminCard"><h2>แก้ไขราคาใบงาน</h2><PricingEditor orderId={orderId} initialItems={items.map(item => ({ id: Number(item.id), lineNo: Number(item.line_no), name: String(item.item_name || `พวงกุญแจ ${item.width_cm} × ${item.height_cm} ซม.`), specification: String(item.product_type) === "custom" ? String(item.item_description || "งานสั่งทำอื่น ๆ") : `${item.width_cm} × ${item.height_cm} ซม. • ${item.thickness_mm} มม. • พิมพ์ ${item.print_sides} ด้าน • อะไหล่ ${item.hardware_code}`, quantity: Number(item.quantity), unitPrice: Number(item.unit_price) }))} initialExtras={adjustments.map(item => ({ id: Number(item.id), label: String(item.label), amount: Number(item.amount) }))} initialDiscount={Number(order.discount_amount || 0)} vatApplied={Number(order.vat_applied) === 1} shippingFee={shippingFee}/></section><section><h2>ค่าจัดส่ง</h2><FinancialForm orderId={orderId} orderSubtotal={Number(order.estimated_subtotal)} vatApplied={Number(order.vat_applied) === 1} initialShipping={shippingFee} initialPaid={paidAmount}/></section></div></details>}
      <details className="orderToolDisclosure orderToolSecondary" id="artwork-tools"><summary><span><b>ไฟล์ต้นฉบับจากลูกค้า</b><small>{order.artwork_key ? String(order.artwork_name) : "ลูกค้าไม่ได้แนบไฟล์"}</small></span><i>ดูไฟล์</i></summary><div className="orderToolBody">{order.external_file_url && <p><a className="downloadArtwork" href={String(order.external_file_url)} target="_blank" rel="noreferrer">เปิด Google Drive ↗</a></p>}{order.artwork_key ? <><p>{String(order.artwork_name)}</p><a className="downloadArtwork" href={`/api/admin/orders/${order.id}/artwork`}>ดาวน์โหลดไฟล์ต้นฉบับ</a></> : <p>ลูกค้าไม่ได้แนบไฟล์</p>}</div></details>
      <details className="orderToolDisclosure orderToolSecondary" id="history-tools"><summary><span><b>ประวัติใบงาน</b><small>สถานะ {history.length} รายการ • การแก้ไข {audits.length} รายการ</small></span><i>ดูประวัติ</i></summary><div className="orderToolBody combinedOrderHistory"><section className="adminHistory"><h3>ประวัติสถานะ</h3>{history.length ? <ol>{history.map((item, index) => <li key={`${item.created_at}-${index}`}><b>{statusLabels[item.status] || item.status}</b><p>{item.note || "อัปเดตสถานะ"}</p><small>{item.created_at}</small></li>)}</ol> : <p>ยังไม่มีประวัติ</p>}</section><section className="adminHistory auditHistory"><h3>ประวัติการแก้ไขโดยทีมงาน</h3>{audits.length ? <ol>{audits.map((item, index) => <li key={`${item.created_at}-${index}`}><b>{item.display_name} <small>@{item.username}</small></b><p>{item.action} — {item.details || "-"}</p><small>{item.created_at}</small></li>)}</ol> : <p>ยังไม่มีการแก้ไข</p>}</section></div></details>
      </div>
    </section>
  </main>;
}
