import { env } from "cloudflare:workers";
import { audit, can, getStaffUser } from "../../../../staff-auth";

export async function POST(request:Request){
 const user=await getStaffUser();if(!user)return Response.json({error:"กรุณาเข้าสู่ระบบ"},{status:401});if(!can(user,"commission:manage"))return Response.json({error:"ไม่มีสิทธิ์ตั้งค่าคอมมิชชั่น"},{status:403});
 const body=await request.json() as {action?:string;id?:number;salesOwnerId?:number|null;tierName?:string;minSales?:number;maxSales?:number|null;ratePercent?:number;effectiveFrom?:string;effectiveTo?:string};const db=(env as unknown as {DB:D1Database}).DB;
 if(body.action==="close"){const id=Number(body.id);if(!Number.isInteger(id)||id<1)return Response.json({error:"เรตไม่ถูกต้อง"},{status:400});await db.prepare("UPDATE commission_tiers SET active=0,effective_to=CASE WHEN effective_to='' OR effective_to>date('now','+7 hours') THEN date('now','+7 hours') ELSE effective_to END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();await audit(user,null,"ปิดเรตคอมมิชชั่น",`tier #${id}`);return Response.json({ok:true})}
 const salesOwnerId=body.salesOwnerId?Number(body.salesOwnerId):null,tierName=String(body.tierName||"").trim().slice(0,60),minSales=Number(body.minSales),maxSales=body.maxSales==null?null:Number(body.maxSales),rate=Number(body.ratePercent),from=String(body.effectiveFrom||""),to=String(body.effectiveTo||"");
 if(salesOwnerId!==null){const found=await db.prepare("SELECT id FROM staff_users WHERE id=? AND active=1 LIMIT 1").bind(salesOwnerId).first();if(!found)return Response.json({error:"ไม่พบเซลล์ที่เลือก"},{status:400})}
 if(!tierName||!Number.isFinite(minSales)||minSales<0||(maxSales!==null&&(!Number.isFinite(maxSales)||maxSales<=minSales))||!Number.isFinite(rate)||rate<0||rate>100||!/^\d{4}-\d{2}-\d{2}$/.test(from)||(to&&(!/^\d{4}-\d{2}-\d{2}$/.test(to)||to<from)))return Response.json({error:"กรุณาตรวจช่วงยอด เปอร์เซ็นต์ และวันที่มีผล"},{status:400});
 const overlap=await db.prepare("SELECT id FROM commission_tiers WHERE COALESCE(sales_owner_id,0)=COALESCE(?,0) AND NOT (COALESCE(max_sales,1e99)<=? OR min_sales>=COALESCE(?,1e99)) AND NOT (effective_to<>'' AND effective_to<?) AND NOT (?<>'' AND effective_from>?) LIMIT 1").bind(salesOwnerId,minSales,maxSales,from,to,to).first();if(overlap)return Response.json({error:"ช่วงยอดและวันที่นี้ทับกับเรตเดิม กรุณาปิดเรตเดิมหรือปรับช่วง"},{status:409});
 await db.prepare("INSERT INTO commission_tiers (sales_owner_id,tier_name,min_sales,max_sales,rate_percent,effective_from,effective_to,created_by_id,created_by_name) VALUES (?,?,?,?,?,?,?,?,?)").bind(salesOwnerId,tierName,minSales,maxSales,rate,from,to,user.id,user.displayName).run();await audit(user,null,"เพิ่มเรตคอมมิชชั่น",`${tierName} • ${salesOwnerId?`user #${salesOwnerId}`:"ทุกคน"} • ${rate}%`);return Response.json({ok:true})
}
