import { env } from "cloudflare:workers";
import { audit,canManagePricing,getStaffUser } from "../../../../../staff-auth";
import { calculateOrderTotals } from "../../../../../order-pricing.mjs";

type Payload={items?:{id:number;unitPrice:number}[];adjustments?:{label:string;amount:number}[];discountAmount?:number};
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
 const user=await getStaffUser();if(!user)return Response.json({error:"กรุณาเข้าสู่ระบบ"},{status:401});if(!canManagePricing(user))return Response.json({error:"ไม่มีสิทธิ์แก้ไขราคาใบงาน"},{status:403});
 const {id}=await params;const orderId=Number(id);if(!Number.isInteger(orderId)||orderId<1)return Response.json({error:"เลขใบงานไม่ถูกต้อง"},{status:400});
 const body=await request.json() as Payload;const submittedItems=Array.isArray(body.items)?body.items:[],submittedExtras=Array.isArray(body.adjustments)?body.adjustments:[];const discount=Number(body.discountAmount??0);
 if(submittedItems.length<1||submittedItems.length>50||submittedExtras.length>20||!Number.isFinite(discount)||discount<0)return Response.json({error:"ข้อมูลราคาไม่ถูกต้อง"},{status:400});
 if(submittedItems.some(item=>!Number.isInteger(Number(item.id))||!validMoney(item.unitPrice))||submittedExtras.some(item=>!item.label?.trim()||item.label.trim().length>120||!validMoney(item.amount)))return Response.json({error:"กรุณาตรวจชื่อและราคาของทุกรายการ"},{status:400});
 const db=(env as unknown as {DB:D1Database}).DB;const order=await db.prepare("SELECT vat_applied,shipping_fee FROM orders WHERE id=?").bind(orderId).first<{vat_applied:number;shipping_fee:string}>();if(!order)return Response.json({error:"ไม่พบใบงาน"},{status:404});
 const stored=(await db.prepare("SELECT id,quantity FROM order_items WHERE order_id=? ORDER BY line_no").bind(orderId).all<{id:number;quantity:number}>()).results;if(stored.length!==submittedItems.length)return Response.json({error:"จำนวนรายการสินค้าไม่ตรงกับใบงาน"},{status:409});
 const priceMap=new Map(submittedItems.map(item=>[Number(item.id),Number(item.unitPrice)]));if(stored.some(item=>!priceMap.has(Number(item.id))))return Response.json({error:"พบรายการสินค้าที่ไม่อยู่ในใบงาน"},{status:409});
 const extras=submittedExtras.map(item=>({label:item.label.trim(),amount:Number(item.amount)}));const lines=stored.map(item=>({quantity:Number(item.quantity),unitPrice:priceMap.get(Number(item.id))!}));const totals=calculateOrderTotals(lines,extras.map(item=>item.amount),discount,Number(order.vat_applied)===1,Number(order.shipping_fee||0));if(discount>totals.grossSubtotal)return Response.json({error:"ส่วนลดต้องไม่เกินยอดสินค้าและรายการเสริม"},{status:400});
 const statements=stored.map(item=>{const unit=priceMap.get(Number(item.id))!;return db.prepare("UPDATE order_items SET unit_price=?,line_total=? WHERE id=? AND order_id=?").bind(unit.toFixed(2),(unit*Number(item.quantity)).toFixed(2),item.id,orderId)});statements.push(db.prepare("DELETE FROM order_adjustments WHERE order_id=?").bind(orderId));for(const extra of extras)statements.push(db.prepare("INSERT INTO order_adjustments (order_id,label,amount,created_by) VALUES (?,?,?,?)").bind(orderId,extra.label,extra.amount.toFixed(2),user.username));statements.push(db.prepare("UPDATE orders SET estimated_unit_price=?,estimated_subtotal=?,discount_amount=?,vat_amount=?,estimated_total=? WHERE id=?").bind((totals.itemSubtotal/Math.max(1,lines.reduce((sum,line)=>sum+line.quantity,0))).toFixed(2),totals.subtotal.toFixed(2),totals.discount.toFixed(2),totals.vatAmount.toFixed(2),totals.total.toFixed(2),orderId));await db.batch(statements);
 const shipping=Number(order.shipping_fee||0),payableTotal=totals.total+shipping;await audit(user,orderId,"แก้ไขราคาใบงาน",`สินค้า ฿${totals.itemSubtotal.toFixed(2)} • รายการเสริม ฿${totals.adjustmentsTotal.toFixed(2)} • ส่วนลด ฿${totals.discount.toFixed(2)} • ค่าส่ง ฿${shipping.toFixed(2)} • ยอดสุทธิ ฿${payableTotal.toFixed(2)}`);return Response.json({ok:true,totals:{...totals,payableTotal}});
}
function validMoney(value:number){const number=Number(value);return Number.isFinite(number)&&number>=0&&number<=1000000}
