import { env, waitUntil } from "cloudflare:workers";
import { notifyNewOrder } from "../../integrations";
import { calculatePrice, type Thickness } from "../../pricing-config";
import { audit, getStaffUser } from "../../staff-auth";
import { calculateCustomLineTotal } from "../../custom-order-item.mjs";
import { getVatCollectionPolicy, vatCollectionDecision } from "../../vat-collection-policy.mjs";
import { syncWorkOrderFromOrder } from "../../work-order-sync";
import { analyzePaymentSlip, markPaymentSlipAnalysisQueued, type PaymentSlipAnalysisEnv } from "../../payment-slip-analysis";

type Database={prepare(sql:string):{bind(...values:unknown[]):{run():Promise<{success:boolean}>;first<T>():Promise<T|null>}}};
type Bucket={put(key:string,value:ArrayBuffer,options?:{httpMetadata?:{contentType?:string}}):Promise<unknown>};
type SubmittedItem={productType:"acrylic_keychain"|"custom";itemName:string;description:string;thickness:string;width:number;height:number;pricingSize:number;quantity:number;sides:number;hardwareCode:string;hardwareName:string;hardwareColor:string;packaging:string;unitPrice:number;lineTotal:number};
const allowed=new Set(["png","jpg","jpeg","pdf","ai","psd","zip"]);
const rushModes=new Set(["normal","urgent"]);
const clean=(v:FormDataEntryValue|null)=>typeof v==="string"?v.trim():"";
const num=(v:FormDataEntryValue|null)=>Number(clean(v));

export async function POST(request:Request){
 try{
  const staffUser=await getStaffUser();if(!staffUser)return Response.json({error:"กรุณาเข้าสู่ระบบทีมงานก่อนสร้างใบงาน"},{status:401});
  const database=(env as unknown as {DB:D1Database}).DB;
  const form=await request.formData();const name=clean(form.get("name"));const phone=clean(form.get("phone"));const digits=phone.replace(/\D/g,"");
  if(!name)return Response.json({error:"กรุณากรอกชื่อผู้ติดต่อ"},{status:400});
  if(digits.length<8||digits.length>15)return Response.json({error:"กรุณาตรวจสอบเบอร์โทรศัพท์"},{status:400});
  const contactChannel=clean(form.get("contact_channel"));const salesChannel=await database.prepare("SELECT code,prefix,name FROM sales_channels WHERE code=? AND active=1 LIMIT 1").bind(contactChannel).first<{code:string;prefix:string;name:string}>();const orderPrefix=String(salesChannel?.prefix||"");if(!salesChannel||!/^[A-Z0-9]{2,6}$/.test(orderPrefix))return Response.json({error:"กรุณาเลือกเพจหรือช่องทางขายที่ใช้งานอยู่"},{status:400});
  const submittedSalesOwnerId=Number(clean(form.get("sales_owner_id"))||staffUser.id);const salesOwner=Number.isInteger(submittedSalesOwnerId)&&submittedSalesOwnerId>0?await database.prepare("SELECT u.id,u.display_name FROM staff_users u WHERE u.id=? AND u.active=1 AND (u.role IN ('admin','production_manager','sales') OR EXISTS (SELECT 1 FROM staff_user_teams t WHERE t.user_id=u.id AND t.team_code='sale')) LIMIT 1").bind(submittedSalesOwnerId).first<{id:number;display_name:string}>():null;if(!salesOwner)return Response.json({error:"กรุณาเลือกเซลล์ผู้รับผิดชอบที่ใช้งานอยู่"},{status:400});
  const sides=num(form.get("print_sides"));const pricingSize=num(form.get("pricing_size_cm"));
  let items:SubmittedItem[]=[];try{const parsed=JSON.parse(clean(form.get("items_json"))||"[]");if(!Array.isArray(parsed)||parsed.length<1||parsed.length>20)throw new Error();items=parsed.map((raw:Record<string,unknown>,index)=>({productType:raw.productType==="custom"?"custom":"acrylic_keychain",itemName:String(raw.itemName||`รายการ ${index+1}`).trim().slice(0,100),description:String(raw.description||"").trim().slice(0,1000),thickness:String(raw.thickness||""),width:Number(raw.width),height:Number(raw.height),pricingSize:Number(raw.pricingSize),quantity:Number(raw.quantity),sides:Number(raw.sides),hardwareCode:String(raw.hardwareCode||""),hardwareName:String(raw.hardwareName||""),hardwareColor:String(raw.hardwareColor||""),packaging:String(raw.packaging||""),unitPrice:Number(raw.unitPrice),lineTotal:Number(raw.lineTotal)}));if(items.some(item=>!item.itemName||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>1000000||!Number.isFinite(item.unitPrice)||item.unitPrice<0||item.unitPrice>10000000||!Number.isFinite(item.lineTotal)||item.lineTotal<0||(item.productType==="custom"?item.description.length<2:(!item.thickness||!Number.isFinite(item.width)||item.width<=0||!Number.isFinite(item.height)||item.height<=0||!Number.isInteger(item.pricingSize)||item.pricingSize<1||![1,2].includes(item.sides)||!item.hardwareCode||!item.hardwareName||!item.packaging))))throw new Error()}catch{return Response.json({error:"ข้อมูลรายการสินค้าไม่ถูกต้อง"},{status:400})}
  const pricingDb=database;const savedPrices=(await pricingDb.prepare("SELECT hardware_code,price FROM hardware_prices").all<{hardware_code:string;price:string}>()).results;const priceOverrides=Object.fromEntries(savedPrices.map(row=>[row.hardware_code,Number(row.price)]));
  items=items.map(item=>{if(item.productType==="custom"){const lineTotal=calculateCustomLineTotal(item.quantity,item.unitPrice);return {...item,thickness:"",width:0,height:0,pricingSize:0,sides:0,hardwareCode:"-",hardwareName:"ไม่ใช้",hardwareColor:"",packaging:"custom_order",lineTotal}}const price=calculatePrice({thickness:item.thickness==="3"?"3":"2.5" as Thickness,width:item.width,height:item.height,quantity:item.quantity,sides:item.sides===2?2:1,hardwareCode:item.hardwareCode,packaging:item.packaging,hardwarePrice:priceOverrides[item.hardwareCode]});return {...item,pricingSize:price.size,unitPrice:price.unit,lineTotal:price.total}});
  const calculatedQuantity=items.reduce((sum,item)=>sum+item.quantity,0);const calculatedSubtotal=Math.round(items.reduce((sum,item)=>sum+item.lineTotal,0)*100)/100;
  const entry=form.get("artwork");const file=entry instanceof File&&entry.size>0?entry:null;let artworkKey="";const slipEntry=form.get("payment_slip");const paymentSlip=slipEntry instanceof File&&slipEntry.size>0?slipEntry:null;let paymentSlipKey="";
  if(file){const ext=file.name.split(".").pop()?.toLowerCase()??"";if(!allowed.has(ext))return Response.json({error:"ประเภทไฟล์งานไม่รองรับ"},{status:400});if(file.size>15*1024*1024)return Response.json({error:"ไฟล์งานต้องมีขนาดไม่เกิน 15 MB"},{status:400})}
  if(paymentSlip){if(!["image/png","image/jpeg","image/webp"].includes(paymentSlip.type))return Response.json({error:"สลิปต้องเป็นไฟล์ PNG, JPG หรือ WEBP"},{status:400});if(paymentSlip.size>8*1024*1024)return Response.json({error:"ภาพสลิปต้องมีขนาดไม่เกิน 8 MB"},{status:400})}
  const requestedDate=clean(form.get("requested_date"));if(!/^\d{4}-\d{2}-\d{2}$/.test(requestedDate))return Response.json({error:"กรุณาเลือกวันส่งงาน"},{status:400});
  const rushMode=clean(form.get("rush_mode")).toLowerCase()||"normal";if(!rushModes.has(rushMode))return Response.json({error:"โหมดเร่งคิวไม่ถูกต้อง"},{status:400});
  const requestedSpeedDays=num(form.get("requested_speed_days"));if(!Number.isInteger(requestedSpeedDays)||requestedSpeedDays<0||requestedSpeedDays>365)return Response.json({error:"จำนวนวันเร่งคิวไม่ถูกต้อง"},{status:400});
  const deliveryTier=clean(form.get("delivery_tier")).slice(0,120);const rushFeeValue=num(form.get("rush_fee"));if(!Number.isFinite(rushFeeValue)||rushFeeValue<0||rushFeeValue>1000000)return Response.json({error:"ค่าบริการเร่งคิวไม่ถูกต้อง"},{status:400});
  const rushNote=clean(form.get("rush_note")).slice(0,400);
  const shippingFee=num(form.get("shipping_fee"));const submittedPaidAmount=num(form.get("deposit_amount"));const paymentStatus=clean(form.get("payment_status"));
  const invoiceChoice=clean(form.get("tax_invoice_requested"));
  if(!["0","1"].includes(invoiceChoice))return Response.json({error:"กรุณาเลือกขอหรือไม่ขอใบกำกับภาษีให้ชัดเจน"},{status:400});
  const vatPolicy=await getVatCollectionPolicy(database);
  if(Number(clean(form.get("vat_policy_revision")))!==vatPolicy.revision)return Response.json({error:"นโยบาย VAT เปลี่ยนแล้ว กรุณาโหลดหน้าใหม่และตรวจยอดก่อนยืนยัน"},{status:409});
  const taxDecision=vatCollectionDecision(vatPolicy.mode,invoiceChoice==="1");
  const vatApplied=taxDecision.addVat?1:0;
  if(clean(form.get("vat_applied"))!==String(vatApplied))return Response.json({error:"ยอด VAT ไม่ตรงกับนโยบายปัจจุบัน กรุณาตรวจยอดใหม่"},{status:409});
  const rushFee = Math.max(0, rushFeeValue);
  const calculatedVat=vatApplied?Math.round((calculatedSubtotal+shippingFee)*7)/100:0;const calculatedTotal=calculatedSubtotal+calculatedVat+rushFee;const payableTotal=calculatedTotal+shippingFee;
  if(!Number.isFinite(shippingFee)||shippingFee<0)return Response.json({error:"กรุณาตรวจสอบค่าจัดส่ง"},{status:400});
  if(!["paid_full","deposit","unpaid"].includes(paymentStatus))return Response.json({error:"กรุณาเลือกสถานะการชำระเงิน"},{status:400});
  let depositAmount=0;
  if(paymentStatus==="paid_full")depositAmount=payableTotal;
  if(paymentStatus==="deposit"){depositAmount=submittedPaidAmount;if(!Number.isFinite(depositAmount)||depositAmount<=0||depositAmount>=payableTotal)return Response.json({error:"ยอดมัดจำต้องมากกว่า 0 และน้อยกว่ายอดสุทธิ"},{status:400})}
  if(paymentStatus!=="unpaid"&&!paymentSlip)return Response.json({error:"กรุณาแนบสลิปสำหรับยอดที่รับชำระ"},{status:400});
  if(paymentStatus==="unpaid"&&paymentSlip)return Response.json({error:"มีสลิปแนบอยู่ กรุณาเลือกชำระเต็มจำนวนหรือชำระมัดจำ"},{status:400});
  const runtime=env as unknown as {DB?:Database;ORDER_FILES?:Bucket};if(!runtime.DB||!runtime.ORDER_FILES)throw new Error("Order storage is unavailable");
  const publicToken=crypto.randomUUID().replaceAll("-","");if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-");artworkKey=`orders/${publicToken}/${safe}`;await runtime.ORDER_FILES.put(artworkKey,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||"application/octet-stream"}})}if(paymentSlip){const safe=paymentSlip.name.replace(/[^a-zA-Z0-9._-]+/g,"-");paymentSlipKey=`payment-slips/${publicToken}/customer-${Date.now()}-${safe}`;await runtime.ORDER_FILES.put(paymentSlipKey,await paymentSlip.arrayBuffer(),{httpMetadata:{contentType:paymentSlip.type}})}
  const fileDeliveryMethod=clean(form.get("file_delivery_method"))||"upload";const externalFileUrl=clean(form.get("external_file_url"));const fileDeliveryNote=clean(form.get("file_delivery_note")).slice(0,500);if(!["upload","google_drive","email"].includes(fileDeliveryMethod))return Response.json({error:"ช่องทางส่งไฟล์ไม่ถูกต้อง"},{status:400});if(externalFileUrl){try{const url=new URL(externalFileUrl);if(url.protocol!=="https:"||!["drive.google.com","docs.google.com"].includes(url.hostname))throw new Error()}catch{return Response.json({error:"กรุณาใส่ลิงก์ Google Drive ที่ถูกต้อง"},{status:400})}}
  const sql=`INSERT INTO orders (order_number,public_token,contact_name,phone,line_id,email,contact_channel,social_contact_name,sales_owner_id,sales_owner_name,file_delivery_method,external_file_url,file_delivery_note,address,province,requested_date,thickness_mm,width_cm,height_cm,pricing_size_cm,quantity,print_sides,hardware_code,hardware_name,hardware_color,packaging_type,rush_mode,requested_speed_days,delivery_tier,rush_fee,rush_note,artwork_name,artwork_key,artwork_type,payment_slip_name,payment_slip_key,payment_slip_type,estimated_unit_price,estimated_subtotal,vat_applied,vat_amount,estimated_total,shipping_fee,deposit_amount,tax_invoice_requested,vat_policy_mode,vat_policy_revision) SELECT ? || '-' || printf('%04d',MAX(1232,COALESCE(MAX(CASE WHEN instr(order_number,'-') BETWEEN 3 AND 7 AND substr(order_number,instr(order_number,'-')+1) GLOB '[0-9]*' THEN CAST(substr(order_number,instr(order_number,'-')+1) AS INTEGER) END),0))+1),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM orders HAVING (SELECT revision FROM vat_collection_settings WHERE id=1)=? RETURNING id,order_number`;
  const saved=await runtime.DB.prepare(sql).bind(orderPrefix,publicToken,name,phone,clean(form.get("line")),clean(form.get("email")),contactChannel,clean(form.get("social_contact_name")),salesOwner.id,salesOwner.display_name,fileDeliveryMethod,externalFileUrl,fileDeliveryNote,clean(form.get("address")),clean(form.get("province")),requestedDate,clean(form.get("thickness_mm")),clean(form.get("width_cm")),clean(form.get("height_cm")),pricingSize,calculatedQuantity,sides,clean(form.get("hardware_code")),clean(form.get("hardware_name")),clean(form.get("hardware_color")),clean(form.get("packaging_type")),rushMode,requestedSpeedDays,deliveryTier,rushFeeValue.toFixed(2),rushNote,file?.name??"",artworkKey,file?.type??"",paymentSlip?.name??"",paymentSlipKey,paymentSlip?.type??"",String(items[0].unitPrice),String(calculatedSubtotal),vatApplied,String(calculatedVat),String(calculatedTotal),shippingFee.toFixed(2),depositAmount.toFixed(2),invoiceChoice==="1"?1:0,vatPolicy.mode,vatPolicy.revision,vatPolicy.revision).first<{id:number;order_number:string}>();
  if(!saved)return Response.json({error:"นโยบาย VAT เปลี่ยนระหว่างบันทึก ยังไม่สร้างใบงาน กรุณาโหลดหน้าใหม่และตรวจยอด"},{status:409});const orderNo=saved.order_number;const paymentSummary=paymentStatus==="paid_full"?`ชำระเต็มจำนวน ฿${depositAmount.toFixed(2)}`:paymentStatus==="deposit"?`รับมัดจำ ฿${depositAmount.toFixed(2)} • ค้าง ฿${(payableTotal-depositAmount).toFixed(2)}`:"ยังไม่ชำระ";
  for(const [index,item] of items.entries())await runtime.DB.prepare("INSERT INTO order_items (order_id,line_no,product_type,item_name,item_description,thickness_mm,width_cm,height_cm,pricing_size_cm,quantity,print_sides,hardware_code,hardware_name,hardware_color,packaging_type,unit_price,line_total) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(saved.id,index+1,item.productType,item.itemName,item.description,item.thickness,String(item.width),String(item.height),item.pricingSize,item.quantity,item.sides,item.hardwareCode,item.hardwareName,item.hardwareColor,item.packaging,String(item.unitPrice),String(item.lineTotal)).run();
  let initialReceiptId:number|null=null;
  if(paymentStatus!=="unpaid"&&paymentSlip&&paymentSlipKey){
   const receipt=await runtime.DB.prepare("INSERT INTO order_payment_receipts (order_id,amount,file_name,file_key,file_type,created_by_id,created_by_name) VALUES (?,?,?,?,?,?,?) RETURNING id").bind(saved.id,depositAmount.toFixed(2),paymentSlip.name,paymentSlipKey,paymentSlip.type,staffUser.id,staffUser.displayName).first<{id:number}>();
   initialReceiptId=receipt?.id??null;
   await runtime.DB.prepare("UPDATE orders SET payment_confirmed_at=CURRENT_TIMESTAMP,payment_confirmed_by=? WHERE id=?").bind(staffUser.displayName,saved.id).run();
  }
  await runtime.DB.prepare("INSERT INTO order_status_history (order_id,status,note) VALUES (?,?,?)").bind(saved.id,"waiting_for_artwork_review",`ฝ่ายขายรับงาน ${items.length} รายการเข้าสู่ระบบแล้ว • เซลล์ ${salesOwner.display_name} • ${paymentSummary}${paymentSlip?" • บันทึกเป็นการชำระงวดที่ 1 แล้ว":""}`).run();await syncWorkOrderFromOrder(runtime.DB as unknown as D1Database,saved.id,{actorId:staffUser.id});await audit(staffUser,saved.id,"สร้างใบงาน",`${orderNo} • เซลล์ ${salesOwner.display_name} • ${items.length} รายการ • ยอดรวม ฿${payableTotal.toFixed(2)} • ${paymentSummary} • เตรียมข้อมูลฝ่ายผลิตอัตโนมัติ`);
  waitUntil(notifyNewOrder(env as never,{id:saved.id,publicToken,orderNumber:orderNo,contactName:name,phone,requestedDate,quantity:calculatedQuantity,estimatedTotal:String(calculatedTotal)}));
  await audit(staffUser,saved.id,"การเรียกเก็บ VAT",`${invoiceChoice==="1"?"ขอใบกำกับภาษีเต็มรูป":"ไม่ขอใบกำกับภาษีเต็มรูป"} • ${taxDecision.addVat?`บวก VAT ฿${calculatedVat.toFixed(2)}`:"ไม่บวกเพิ่มกับลูกค้า — รอฝ่ายบัญชีแยกภาษี ไม่ใช่ยอดยกเว้นภาษี"} • ${vatPolicy.mode} revision ${vatPolicy.revision}`);
  if(paymentSlip&&paymentSlipKey){const analysisRuntime=env as unknown as PaymentSlipAnalysisEnv;const analysisInput={orderId:saved.id,receiptId:initialReceiptId,fileKey:paymentSlipKey,fileName:paymentSlip.name,expectedAmount:depositAmount};await markPaymentSlipAnalysisQueued(analysisRuntime,analysisInput);waitUntil(analyzePaymentSlip(analysisRuntime,analysisInput))}
  return Response.json({orderId:saved.id,orderNumber:orderNo,publicToken,trackingPath:`/track/${publicToken}`,documentPath:`/order/${publicToken}`,artworkUploaded:Boolean(file)},{status:201});
 }catch(error){console.error("order submission failed",error);return Response.json({error:"ไม่สามารถสร้างใบสั่งงานได้ กรุณาลองอีกครั้งหรือติดต่อ LINE @k2sign"},{status:500})}
}
